In [1]:
import matplotlib.pyplot as plt
from math import exp
from scipy.stats import norm
from scipy import stats
import seaborn as sns
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
plt.rcParams["figure.figsize"] = [10,5]
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_al = pd.read_csv('unix_pny/ny_pop.csv')

In [3]:
df_paul = pd.read_csv('unix_pny/ny_pop.csv')

### Need to be finished pipeline function

def kelevin(df, df_):
    def paul_pipeline(df):
        df['CIT_STATUS'] = np.where(df['CIT'] != 5, 1, 0)
        df['BORN_CIT'] = np.where((df['CITWP'].isna()) & ((df['CIT'] != 4) & (df['CIT'] != 5)), 1, 0)
        conditions = [ (df['CIT_STATUS'] == 1),(df['CIT_STATUS'] == 0)]
        choices = [0,1]
        df['CITWP'] = np.select(conditions, choices, df['CITWP'] )
        conditions = [(df['AGEP'] < 15),((df['AGEP'] >= 15) & (df['COW'].isna()))]
        choices = [0,10]
        df['COW'] = np.select(conditions, choices, df['COW'] )
        conditions = [ (df['AGEP'] < 5)]
        choices = [0]
        df['DDRS'] = np.select(conditions, choices, df['DDRS'] )
        conditions = [ (df['AGEP'] < 5)]
        choices = [0]
        df['DPHY'] = np.select(conditions, choices, df['DPHY'] )
        conditions = [ (df['AGEP'] < 5)]
        choices = [0]
        df['DREM'] = np.select(conditions, choices, df['DREM'] )
        df['ENG'] = np.where(df['AGEP'] < 5, 1, df['ENG'])
        df['ENG'] = np.where(df['ENG'].isna(), 5, df['ENG'])
        conditions = [ (df['ESR'] == 3) & (df['JWMNP'].isna()),df['JWMNP'].isna()]
        choices = [0,201]
        df['JWMNP'] = np.select(conditions, choices, df['JWMNP'] )
        df['JWRIP'] = np.where(df['JWRIP'].isna(), 0, df['JWRIP'] )
        conditions = [ df['AGEP'] < 15,(df['ESR'] == 3) & (df['JWMNP'].isna())]
        choices = [0,13]
        df['JWTR'] = np.select(conditions, choices, df['JWTR'] )
        df['JWTR'] = np.where(df['JWTR'].isna(), 14, df['JWTR'] )
        df['MARHD'] = np.where(df['AGEP'] < 15, 0, df['MARHD'] )
        df['MARHD'] = np.where(df['MARHD'].isna(), 3, df['MARHD'] )
        df['MARHM'] = np.where(df['AGEP'] < 15, 0, df['MARHM'] )
        df['MARHM'] = np.where(df['MARHM'].isna(), 3, df['MARHM'] )
        df['MARHT'] = np.where(df['AGEP'] < 15, 0, df['MARHT'] )
        df['MARHT'] = np.where(df['MARHD'].isna(), 4, df['MARHD'] )
        df['MARHYP'] = np.where(df['AGEP'] < 15, 0, df['MARHYP'] )
        df['MARHYP'] = np.where(df['MARHYP'].isna(), 1, df['MARHYP'] )
        df['MIG'] = np.where(df['AGEP'] < 1, 0, df['MIG'] )
        conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
        choices = [2,3,4]
        df['MLPCD'] = np.select(conditions, choices, df['MLPCD'] )
        conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
        choices = [2,3,4]
        df['MLPE'] = np.select(conditions, choices, df['MLPE'] )
        conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
        choices = [2,3,4]
        df['MLPFG'] = np.select(conditions, choices, df['MLPFG'] )
        conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
        choices = [2,3,4]
        df['MLPH'] = np.select(conditions, choices, df['MLPH'] )
        conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
        choices = [2,3,4]
        df['MLPI'] = np.select(conditions, choices, df['MLPI'] )
        conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
        choices = [2,3,4]
        df['MLPJ'] = np.select(conditions, choices, df['MLPJ'] )
        conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
        choices = [2,3,4]
        df['MLPK'] = np.select(conditions, choices, df['MLPK'] )
        conditions = [ df['AGEP'] < 16,(df['ESR'] != 3) & (df['ESR'].notna())]
        choices = [0,4]
        df['NWLK'] = np.select(conditions, choices, df['NWLK'] )
        df['NWLK'] = np.where(df['NWLK'].isna(), 5, df['NWLK'] )
        df['SCH'] = np.where(df['SCH'].isna(),0,df['SCH'])
        df['DECADE'] = np.where(df['BORN_CIT'] == 1, 0, df['DECADE'])
        df['ESP'] = np.where(df['ESP'].isna(),0,df['ESP'])
        conditions = [ df['ESR'] ==3,(df['ESR'] != 3) & (df['ESR'].notna()) & (df['ESR'] != 6)]
        choices = [0,4]
        df['JWDP'] = np.select(conditions, choices, df['JWDP'] )
        df['JWDP'] = np.where(df['JWDP'].isna(),0,df['JWDP'])
        df['MIGSP'] = np.where(df['AGEP'] < 1,0,df['ST'])
        df['MSP'] = np.where(df['AGEP'] < 15,0,df['MSP'])
        df['NOP'] = np.where(df['NOP'].isna(),0,df['NOP'])
        df['OC'] = np.where(df['OC'].isna(),0,df['OC'])
        df['OCCP'] = np.where(df['AGEP'] < 16,0,df['OCCP'])
        df['OCCP'] = np.where(df['OCCP'].isna(),1,df['OCCP'])
        df['RC'] = np.where(df['RC'].isna(),3,df['RC'])
        df['SCIENGP'] = np.where(df['SCIENGP'].isna(),0,df['SCIENGP'])
        df['VPS'] = np.where(df['AGEP'] < 17,0,df['VPS'])
        df['VPS'] = np.where((df['MIL'] !=1) |(df['MIL'] !=2) ,16,df['VPS'])
        df['PAP'] = np.where(df['PAP'].isna(),0,df['PAP'])
        df['SSP'] = np.where(df['SSP'].isna(),0,df['SSP'])
        df['WKHP'] = np.where(df['WKHP'].isna(),0,df['WKHP'])
        df['WAGP'] = np.where(df['WAGP'].isna(),0,df['WAGP'])
        df['PERNP'] = np.where(df['PERNP'].isna(),0,df['PERNP'])
        df['PINCP'] = np.where(df['PINCP'].isna(),0,df['PINCP'])
        
        return df
    def transform_INDP(df):
        dataframe = df.copy()
        dataframe['INDP'].fillna('None', inplace=True)
        dataframe['INDP'] = dataframe['INDP'].astype('str')
        conditions = [
            dataframe['INDP'].str.startswith('01'),
            dataframe['INDP'].str.startswith('02'),
            dataframe['INDP'].str.startswith('03'),
            dataframe['INDP'].str.startswith('04'),
            dataframe['INDP'].str.startswith('05'),
            dataframe['INDP'].str.startswith('06'),
            dataframe['INDP'].str.startswith('07'),
            dataframe['INDP'].str.startswith('10'),
            dataframe['INDP'].str.startswith('11'),
            dataframe['INDP'].str.startswith('12'),
            dataframe['INDP'].str.startswith('13'),
            dataframe['INDP'].str.startswith('14'),
            dataframe['INDP'].str.startswith('15'),
            dataframe['INDP'].str.startswith('16'),
            dataframe['INDP'].str.startswith('17'),
            dataframe['INDP'].str.startswith('18'),#16
            dataframe['INDP'].str.startswith('19'),
            dataframe['INDP'].str.startswith('20'),
            dataframe['INDP'].str.startswith('21'),
            dataframe['INDP'].str.startswith('22'),#20
            dataframe['INDP'].str.startswith('23'),
            dataframe['INDP'].str.startswith('24'),
            dataframe['INDP'].str.startswith('25'),
            dataframe['INDP'].str.startswith('26'),
            dataframe['INDP'].str.startswith('27'),
            dataframe['INDP'].str.startswith('28'),
            dataframe['INDP'].str.startswith('29'),
            dataframe['INDP'].str.startswith('30'),#28
            dataframe['INDP'].str.startswith('31'),
            dataframe['INDP'].str.startswith('32'),
            dataframe['INDP'].str.startswith('33'),
            dataframe['INDP'].str.startswith('34'),
            dataframe['INDP'].str.startswith('35'),
            dataframe['INDP'].str.startswith('36'),
            dataframe['INDP'].str.startswith('37'),
            dataframe['INDP'].str.startswith('38'),
            dataframe['INDP'].str.startswith('39'),
            dataframe['INDP'].str.startswith('40'),#38
            dataframe['INDP'].str.startswith('41'),
            dataframe['INDP'].str.startswith('42'),#40
            dataframe['INDP'].str.startswith('43'),
            dataframe['INDP'].str.startswith('44'),
            dataframe['INDP'].str.startswith('45'),
            dataframe['INDP'].str.startswith('46'),
            dataframe['INDP'].str.startswith('47'),
            dataframe['INDP'].str.startswith('48'),
            dataframe['INDP'].str.startswith('49'),
            dataframe['INDP'].str.startswith('50'),
            dataframe['INDP'].str.startswith('51'),
            dataframe['INDP'].str.startswith('52'),
            dataframe['INDP'].str.startswith('53'),
            dataframe['INDP'].str.startswith('54'),
            dataframe['INDP'].str.startswith('55'),
            dataframe['INDP'].str.startswith('56'),
            dataframe['INDP'].str.startswith('57'),
            dataframe['INDP'].str.startswith('60'),
            dataframe['INDP'].str.startswith('61'),
            dataframe['INDP'].str.startswith('62'),
            dataframe['INDP'].str.startswith('63'),
            dataframe['INDP'].str.startswith('64'),#20
            dataframe['INDP'].str.startswith('65'),
            dataframe['INDP'].str.startswith('66'),
            dataframe['INDP'].str.startswith('67'),
            dataframe['INDP'].str.startswith('68'),
            dataframe['INDP'].str.startswith('69'),
            dataframe['INDP'].str.startswith('70'),
            dataframe['INDP'].str.startswith('71'),
            dataframe['INDP'].str.startswith('72'),
            dataframe['INDP'].str.startswith('73'),
            dataframe['INDP'].str.startswith('74'),
            dataframe['INDP'].str.startswith('75'),
            dataframe['INDP'].str.startswith('76'),
            dataframe['INDP'].str.startswith('77'),
            dataframe['INDP'].str.startswith('78'),
            dataframe['INDP'].str.startswith('79'),
            dataframe['INDP'].str.startswith('80'),
            dataframe['INDP'].str.startswith('81'),
            dataframe['INDP'].str.startswith('82'),
            dataframe['INDP'].str.startswith('83'),
            dataframe['INDP'].str.startswith('84'),#20
            dataframe['INDP'].str.startswith('85'),
            dataframe['INDP'].str.startswith('86'),
            dataframe['INDP'].str.startswith('87'),
            dataframe['INDP'].str.startswith('88'),
            dataframe['INDP'].str.startswith('89'),
            dataframe['INDP'].str.startswith('90'),
            dataframe['INDP'].str.startswith('91'),
            dataframe['INDP'].str.startswith('92'),
            dataframe['INDP'].str.startswith('93'),
            dataframe['INDP'].str.startswith('94'),
            dataframe['INDP'].str.startswith('95'),
            dataframe['INDP'].str.startswith('96'),
            dataframe['INDP'].str.startswith('97'),
            dataframe['INDP'].str.startswith('98'),
            dataframe['INDP'].str.startswith('99'),#1
        ]
        choices = [
            'AGR1','AGR2','EXT1','EXT2','UTL1','UTL2','CON','MFG1','MFG2','MFG3','MFG4','MFG5','MFG6','MFG7','MFG8','MFG9','MFG10','MFG11','MFG12','MFG13',
        'MFG14','MFG15','MFG16','MFG17','MFG18','MFG19','MFG20','MFG21','MFG22','MFG23','MFG24','MFG25','MFG26','MFG27','MFG28','MFG29','MFG30','WHL1','WHL2',
        'WHL3','WHL4','WHL5','WHL6','RET1','RET2','RET3','RET4','RET5','RET6','RET7','RET8','RET9','RET10','RET11','RET12','TRN1','TRN2','TRN3','TRN4','INF1','INF2','INF3',
        'INF4','FIN1','FIN2','FIN3','FIN4','PRF1','PRF2','PRF3','PRF4','PRF5','PRF6','EDU','MED1','MED2','MED3','MED4','SCA1','SCA2','ENT1','ENT2','SRV1','SRV2','SRV3','SRV4','SRV5','SRV6','ADM1','ADM2','ADM3','MIL1','MIL2','MIL3',
        'None']
        dataframe['INDP'] = np.select(conditions,choices, 'None')
        df = dataframe
        return df
    def alberts_turn(df_):
        dataframe = df_.copy()
        conditions = [dataframe['DOUT'].eq(1), dataframe['DOUT'].eq(2)
        choices = ['Yes', 'No']
        dataframe['DOUT_cat'] = np.select(conditions, choices, 'LT_15yrs')
        conditions = [dataframe['FER'].eq(1), dataframe['FER'].eq(2)]
        choices = ['Yes', 'No']
        dataframe['FER_cat'] = np.select(conditions, choices, 'Not_Applicable')
        dataframe['INTP_cat'] = np.where(dataframe['INTP'].isna(), 0, dataframe['INTP'])
        conditions = [dataframe['LANX'].eq(1), dataframe['LANX'].eq(2)]
        choices = ['Other_Lang', 'English_Lang']
        dataframe['LANX_cat'] = np.select(conditions, choices, 'Baby_Lang')
        dataframe['MARHW_cat'] = np.where(dataframe['MARHW'].isna(), 'Unknown', dataframe['MARHW'])
        conditions = [dataframe['MIL'].eq(1), dataframe['MIL'].eq(2), dataframe['MIL'].eq(3), dataframe['MIL'].eq(4)]
        choices = ['Cur_Active', 'Past_Active', 'Cond_Active', 'Never_Served']
        dataframe['MIL_cat'] = np.select(conditions, choices, 'LT_17yrold')
        conditions = [dataframe['MLPA'].eq(0), dataframe['MLPA'].eq(1)]
        choices = ['No_Served', 'Yes_Served']
        dataframe['MLPA_cat'] = np.select(conditions, choices, 'LT_17yrold')
        dataframe['OIP_cat'] = np.where(dataframe['OIP'].isna(), 0, dataframe['OIP'])
        dataframe['RETP_cat'] = np.where(dataframe['RETP'].isna(), 0 , dataframe['RETP'])
        conditions = [
            dataframe['SCHG'].eq(1), dataframe['SCHG'].eq(2), dataframe['SCHG'].eq(3), dataframe['SCHG'].eq(4), 
            dataframe['SCHG'].eq(5), dataframe['SCHG'].eq(6), dataframe['SCHG'].eq(7), dataframe['SCHG'].eq(8), 
            dataframe['SCHG'].eq(9), dataframe['SCHG'].eq(10), dataframe['SCHG'].eq(11), dataframe['SCHG'].eq(12),
            dataframe['SCHG'].eq(13), dataframe['SCHG'].eq(14), dataframe['SCHG'].eq(15), dataframe['SCHG'].eq(16)
        ]
        choices = [
            'Nursery', 'Kindergarten', 'Grade_1', 'Grade_2',
            'Grade_3', 'Grade_4', 'Grade_5', 'Grade_6',
            'Grade_7', 'Grade_8', 'Grade_9', 'Grade_10',
            'Grade_11', 'Grade_12', 'Undergrad', 'Graduate'
        ]
        dataframe['SCHG_cat'] = np.select(conditions,choices, 'Not_Attending')
        conditions = [
            dataframe['SCHL'].eq(1), dataframe['SCHL'].eq(2), dataframe['SCHL'].eq(3), dataframe['SCHL'].eq(4), 
            dataframe['SCHL'].eq(5), dataframe['SCHL'].eq(6), dataframe['SCHL'].eq(7), dataframe['SCHL'].eq(8), 
            dataframe['SCHL'].eq(9), dataframe['SCHL'].eq(10), dataframe['SCHL'].eq(11), dataframe['SCHL'].eq(12),
            dataframe['SCHL'].eq(13), dataframe['SCHL'].eq(14), dataframe['SCHL'].eq(15), dataframe['SCHL'].eq(16),
            dataframe['SCHL'].eq(17), dataframe['SCHL'].eq(18), dataframe['SCHL'].eq(19), dataframe['SCHL'].eq(20),
            dataframe['SCHL'].eq(21), dataframe['SCHL'].eq(22), dataframe['SCHL'].eq(23), dataframe['SCHL'].eq(24)
        ]
        choices = [
            'No_School', 'Nursery', 'Kindergarten', 'Grade_1', 
            'Grade_2', 'Grade_3', 'Grade_4', 'Grade_5', 
            'Grade_6', 'Grade_7', 'Grade_8', 'Grade_9', 
            'Grade_10', 'Grade_11', 'Grade_12', 'HS_Diploma', 
            'GED_alt', 'LT1_College', 'NoDegree_College','Associates', ' Bachelors', 'Masters', 'Professional', 'Doctorate'
        ]
        dataframe['SCHL_cat'] = np.select(conditions, choices, 'LT_3yrold')
        dataframe['SEMP_cat'] = np.where(dataframe['SEMP'].isna(), 0, dataframe['SEMP'])
        dataframe['SSIP_cat'] = np.where(dataframe['SSIP'].isna(), 0 , dataframe['SSIP'])
        conditions = [dataframe['WKL'].eq(1), dataframe['WKL'].eq(2), dataframe['WKL'].eq(3)]
        choices = ['LT1', 'BT1_5', 'GT5']
        dataframe['WKL_cat'] = np.select(conditions, choices, 'LT_16yrsold')
        conditions = [
            dataframe['WKW'].eq(1), dataframe['WKW'].eq(2), dataframe['WKW'].eq(3),
            dataframe['WKW'].eq(4), dataframe['WKW'].eq(5), dataframe['WKW'].eq(6)
        ]
        choices = [
            '50_52wks', '48_49wks', '40_47wks',
            '27_39wks', '14_26wks', 'LT_14wks'
        ]
    
    dataframe['WKW_cat'] = np.select(conditions, choices, 'Not_Worked')
    
    # WRK
    conditions = [dataframe['WRK'].eq(1), dataframe['WRK'].eq(2)]
    choices = ['Worked', 'Not_Worked']
    
    dataframe['WRK_cat'] = np.select(conditions, choices, 'Not_Reported')
    
    # YR_ENTER_US
    conditions = [
        dataframe['YOEP'].lt(1949.1), 
        dataframe['YOEP'].lt(1959.1) & dataframe['YOEP'].gt(1949.9),
        dataframe['YOEP'].lt(1969.1) & dataframe['YOEP'].gt(1959.9),
        dataframe['YOEP'].lt(1979.1) & dataframe['YOEP'].gt(1969.9),
        dataframe['YOEP'].lt(1989.1) & dataframe['YOEP'].gt(1979.9),
        dataframe['YOEP'].lt(1999.1) & dataframe['YOEP'].gt(1989.9),
        dataframe['YOEP'].lt(2009.1) & dataframe['YOEP'].gt(1999.9),
        dataframe['YOEP'].lt(2019.1) & dataframe['YOEP'].gt(2009.9),
        dataframe['YOEP'].isna()
    ]
    choices = [
        'Below_50s',
        'Immigr_50s',
        'Immigr_60s',
        'Immigr_70s',
        'Immigr_80s',
        'Immigr_90s',
        'Immigr_00s',
        'Immigr_10s',
        'Naturalized'
    ]
    
    dataframe['YOEP_cat'] = np.select(conditions,choices, 'Unknown')
    
    # ANC
    # Keep ANC as is dataframe['ANC']
    
    # ANCES1
    # Keep ANCES1 as is dataframe['ANC1P']
    
    # ANC2P
    # Keep ANC2P as is dataframe['ANC2P']
    
    
    # DRIVESP
    conditions = [dataframe['DRIVESP'].eq(1), dataframe['DRIVESP'].eq(2), dataframe['DRIVESP'].eq(3),
                 dataframe['DRIVESP'].eq(4), dataframe['DRIVESP'].eq(5), dataframe['DRIVESP'].eq(6)]
    choices = ['1_driver', '2_driver', '3_driver',
              '4_driver', '5_6_driver', 'GT7_driver']
    
    dataframe['DRIVESP_cat'] = np.select(conditions, choices, 'No_Drive')
    

    
    # ESR
    conditions = [dataframe['ESR'].eq(1), dataframe['ESR'].eq(2), dataframe['ESR'].eq(3),
                 dataframe['ESR'].eq(4), dataframe['ESR'].eq(5), dataframe['ESR'].eq(6)]
    choices = ['Employed_at_work', 'Employed_not_work', 'Unemployed',
              'ArmedForces_at_work', 'ArmedForces_not_work', 'Not_Labor']
    
    dataframe['ESR_cat'] = np.select(conditions, choices, 'LT_16yrsold')
    
    # DEGREE1
    # dataframe.drop(columns=['FOD1P'], inplace=True)
    
    # DEGREE2
    # dataframe.drop(columns=['FOD2P'], inplace=True)
    
    # WK_ARR_TME
    # Keep WK_ARR_TIME as is dataframe['JWAP']
    
    # LAN_HOME
    # dataframe.drop(columns=['LANP'], inplace=True)
    
    # MIGPUMA
    # dataframe.drop(columns=['MIGPUMA'], inplace=True)
    
    # NAICSP
    dataframe['NAICSP'].fillna('None', inplace=True)
    conditions = [
        dataframe['NAICSP'].str.startswith('11'),
        dataframe['NAICSP'].str.startswith('21'),
        dataframe['NAICSP'].str.startswith('22'),
        dataframe['NAICSP'].str.startswith('23'),
        dataframe['NAICSP'].str.startswith('31'),
        dataframe['NAICSP'].str.startswith('32'),
        dataframe['NAICSP'].str.startswith('33'),
        dataframe['NAICSP'].str.startswith('3M'),
        dataframe['NAICSP'].str.startswith('42'),
        dataframe['NAICSP'].str.startswith('44'),
        dataframe['NAICSP'].str.startswith('45'),
        dataframe['NAICSP'].str.startswith('4M'),
        dataframe['NAICSP'].str.startswith('51'),
        dataframe['NAICSP'].str.startswith('52'),
        dataframe['NAICSP'].str.startswith('53'),
        dataframe['NAICSP'].str.startswith('54'),
        dataframe['NAICSP'].str.startswith('55'),
        dataframe['NAICSP'].str.startswith('56'),
        dataframe['NAICSP'].str.startswith('61'),
        dataframe['NAICSP'].str.startswith('62'),
        dataframe['NAICSP'].str.startswith('71'),
        dataframe['NAICSP'].str.startswith('72'),
        dataframe['NAICSP'].str.startswith('81'),
        dataframe['NAICSP'].str.startswith('92'),
        dataframe['NAICSP'].str.startswith('99'),
    ]
    choices = [
        'AGR',
        'EXT',
        'UTL',
        'CON',
        'MFG1',
        'MFG2',
        'MFG3',
        'MFG3',
        'WHL',
        'RET1',
        'RET2',
        'RET2',
        'INF',
        'FIN1',
        'FIN2',
        'PRF1',
        'PRF2',
        'PRF3',
        'EDU',
        'MED',
        'ENT1',
        'ENT2',
        'SRV',
        'ADM',
        'No_Work'
    ]
    
    dataframe['NAICSP_cat'] = np.select(conditions, choices, 'No_Work')
    
    # NATIVITY
    # Keep NATIVITY as is dataframe['NATIVITY']
    
    # PAOC
    # dataframe.drop(columns=['PAOC'], inplace=True)
    

    # POBP
    dataframe['POBP_cat'] = np.where(dataframe['POBP'].eq(36), 1, 0)
    
    
    # POWSP
    dataframe['POWSP_cat'] = np.where(dataframe['POWSP'].eq(36), 1, 0)
    
    # PRIVCOV
    # dataframe.drop(columns=['PRIVCOV'], inplace=True)
    
    # PUBCOV
    # dataframe.drop(columns=['PUBCOV'], inplace=True)
    
    # RAC1P
    conditions = [
        dataframe['RAC1P'].eq(1), dataframe['RAC1P'].eq(2), dataframe['RAC1P'].eq(3),
        dataframe['RAC1P'].eq(4), dataframe['RAC1P'].eq(5), dataframe['RAC1P'].eq(6),
        dataframe['RAC1P'].eq(7), dataframe['RAC1P'].eq(8), dataframe['RAC1P'].eq(9),
    ]
    choices = [
        'White', 'Black', 'American_Indian',
        'Alaska_Native', 'American_Indian',' Asian',
        'Native_Hawaii', 'Some_Other', 'GT2_race'
    ]
    
    dataframe['RAC1P_cat'] = np.select(conditions, choices, 'Unknown')
    
    # RAC2P
    # dataframe.drop(columns=['RAC2P'], inplace=True)
    
    # RAC3P
    # dataframe.drop(columns=['RAC3P'], inplace=True)
    
    # RACAIAN
    # Keep as is
    
    # RACASN
    # Keep as is
    
    # RACBLK
    # Keep as is
    
    # RACNH
    # Keep as is
    
    # RACNUM
    # Keep as is
    
    # RACPI
    # Keep as is
    
    # RACSOR
    # Keep as is
    
    # SCIENGRLP
    conditions = [dataframe['SCIENGRLP'].eq(1), dataframe['SCIENGRLP'].eq(2)]
    choices = ['Yes', 'No']
    
    dataframe['SCIENGRLP_cat'] = np.select(conditions, choices, 'LT_Bachelors')
    
    # SFN
    # dataframe.drop(columns = ['SFN'], inplace=True)
    
    # SFR
    # dataframe.drop(columns=['SFR'], inplace=True)
    
    # SOCP
    
    dataframe['SOCP'].fillna('None', inplace=True)
    conditions = [
        dataframe['SOCP'].str.startswith('111'),
        dataframe['SOCP'].str.startswith('112'),
        dataframe['SOCP'].str.startswith('113'),
        dataframe['SOCP'].str.startswith('119'),
        dataframe['SOCP'].str.startswith('131'),
        dataframe['SOCP'].str.startswith('132'),
        dataframe['SOCP'].str.startswith('151'),
        dataframe['SOCP'].str.startswith('152'),
        dataframe['SOCP'].str.startswith('171'),
        dataframe['SOCP'].str.startswith('172'),
        dataframe['SOCP'].str.startswith('173'),
        dataframe['SOCP'].str.startswith('191'),
        dataframe['SOCP'].str.startswith('192'),
        dataframe['SOCP'].str.startswith('193'),
        dataframe['SOCP'].str.startswith('194'),
        dataframe['SOCP'].str.startswith('195'),
        dataframe['SOCP'].str.startswith('211'),
        dataframe['SOCP'].str.startswith('212'),
        dataframe['SOCP'].str.startswith('231'),
        dataframe['SOCP'].str.startswith('232'),#20
        dataframe['SOCP'].str.startswith('251'),
        dataframe['SOCP'].str.startswith('252'),
        dataframe['SOCP'].str.startswith('253'),
        dataframe['SOCP'].str.startswith('254'),
        dataframe['SOCP'].str.startswith('259'),
        dataframe['SOCP'].str.startswith('271'),
        dataframe['SOCP'].str.startswith('272'),
        dataframe['SOCP'].str.startswith('273'),
        dataframe['SOCP'].str.startswith('274'),
        dataframe['SOCP'].str.startswith('291'),
        dataframe['SOCP'].str.startswith('292'),
        dataframe['SOCP'].str.startswith('299'),
        dataframe['SOCP'].str.startswith('311'),
        dataframe['SOCP'].str.startswith('312'),
        dataframe['SOCP'].str.startswith('319'),
        dataframe['SOCP'].str.startswith('331'),
        dataframe['SOCP'].str.startswith('332'),
        dataframe['SOCP'].str.startswith('333'),
        dataframe['SOCP'].str.startswith('339'),
        dataframe['SOCP'].str.startswith('351'),#20
        dataframe['SOCP'].str.startswith('352'),
        dataframe['SOCP'].str.startswith('353'),
        dataframe['SOCP'].str.startswith('359'),
        dataframe['SOCP'].str.startswith('371'),
        dataframe['SOCP'].str.startswith('372'),
        dataframe['SOCP'].str.startswith('373'),
        dataframe['SOCP'].str.startswith('391'),
        dataframe['SOCP'].str.startswith('392'),
        dataframe['SOCP'].str.startswith('393'),
        dataframe['SOCP'].str.startswith('394'),
        dataframe['SOCP'].str.startswith('395'),
        dataframe['SOCP'].str.startswith('396'),
        dataframe['SOCP'].str.startswith('397'),
        dataframe['SOCP'].str.startswith('399'),
        dataframe['SOCP'].str.startswith('411'),
        dataframe['SOCP'].str.startswith('412'),
        dataframe['SOCP'].str.startswith('413'),
        dataframe['SOCP'].str.startswith('414'),
        dataframe['SOCP'].str.startswith('419'),
        dataframe['SOCP'].str.startswith('431'),#20
        dataframe['SOCP'].str.startswith('432'),
        dataframe['SOCP'].str.startswith('433'),
        dataframe['SOCP'].str.startswith('434'),
        dataframe['SOCP'].str.startswith('435'),
        dataframe['SOCP'].str.startswith('436'),
        dataframe['SOCP'].str.startswith('439'),
        dataframe['SOCP'].str.startswith('451'),
        dataframe['SOCP'].str.startswith('452'),
        dataframe['SOCP'].str.startswith('453'),
        dataframe['SOCP'].str.startswith('454'),
        dataframe['SOCP'].str.startswith('471'),
        dataframe['SOCP'].str.startswith('472'),
        dataframe['SOCP'].str.startswith('473'),
        dataframe['SOCP'].str.startswith('474'),
        dataframe['SOCP'].str.startswith('475'),
        dataframe['SOCP'].str.startswith('491'),
        dataframe['SOCP'].str.startswith('492'),
        dataframe['SOCP'].str.startswith('493'),
        dataframe['SOCP'].str.startswith('499'),
        dataframe['SOCP'].str.startswith('511'),#20
        dataframe['SOCP'].str.startswith('512'),
        dataframe['SOCP'].str.startswith('513'),
        dataframe['SOCP'].str.startswith('514'),
        dataframe['SOCP'].str.startswith('515'),
        dataframe['SOCP'].str.startswith('516'),
        dataframe['SOCP'].str.startswith('517'),
        dataframe['SOCP'].str.startswith('518'),
        dataframe['SOCP'].str.startswith('519'),
        dataframe['SOCP'].str.startswith('531'),
        dataframe['SOCP'].str.startswith('532'),
        dataframe['SOCP'].str.startswith('533'),
        dataframe['SOCP'].str.startswith('534'),
        dataframe['SOCP'].str.startswith('535'),
        dataframe['SOCP'].str.startswith('536'),
        dataframe['SOCP'].str.startswith('537'),
        dataframe['SOCP'].str.startswith('551'),
        dataframe['SOCP'].str.startswith('552'),
        dataframe['SOCP'].str.startswith('553'),
        dataframe['SOCP'].str.startswith('559'),
        dataframe['SOCP'].str.startswith('999'),#20
    ]
    choices = [
        'MGR1',
        'MGR2',
        'MGR3',
        'MGR4',
        'BUS1',
        'FIN1',
        'CMM1',
        'CMM2',
        'ENG1',
        'ENG2',
        'ENG3',
        'SCI1',
        'SCI2',
        'SCI3',
        'SCI4',
        'SCI5',
        'CMS1',
        'CMS2',
        'LGL1',
        'LGL2',#20
        'EDU1',
        'EDU2',
        'EDU3',
        'EDU4',
        'EDU5',
        'ENT1',
        'ENT2',
        'ENT3',
        'ENT4',
        'MED1',
        'MED2',
        'MED3',
        'HLS1',
        'HLS2',
        'HLS3',
        'PRT1',
        'PRT2',
        'PRT3',
        'PRT4',
        'EAT1',#20
        'EAT2',
        'EAT3',
        'EAT4',
        'CLN1',
        'CLN2',
        'CLN3',
        'PRS1',
        'PRS2',
        'PRS3',
        'PRS4',
        'PRS5',
        'PRS6',
        'PRS7',
        'PRS8',
        'SAL1',
        'SAL2',
        'SAL3',
        'SAL4',
        'SAL5',
        'OFF1',#20
        'OFF2',
        'OFF3',
        'OFF4',
        'OFF5',
        'OFF6',
        'OFF7',
        'FFF1',
        'FFF2',
        'FFF3',
        'FFF4',
        'EXT1',
        'EXT2',
        'EXT3',
        'EXT4',
        'EXT5',
        'PPR1',
        'PPR2',
        'PPR3',
        'PPR4',
        'PRD1',#20
        'PRD2',
        'PRD3',
        'PRD4',
        'PRD5',
        'PRD6',
        'PRD7',
        'PRD8',
        'PRD9',
        'TRN1',
        'TRN2',
        'TRN3',
        'TRN4',
        'TRN5',
        'TRN6',
        'TRN7',
        'MIL1',
        'MIL2',
        'MIL3',
        'MIL4',
        'No_Work'
    ]
    
    dataframe['SOCP_cat'] = np.select(conditions, choices, 'No_Work')
    
    #drop all flags and weights
#     dataframe.drop(columns =['FCITP', 'FDEYEP', 'FDOUTP',
#        'FDPHYP', 'FDREMP', 'FENGP', 'FFERP', 'FFODP', 'FGCLP', 'FHINS1P',
#        'FHINS3C', 'FHINS3P', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FINTP',
#        'FJWDP', 'FJWRIP', 'FJWTRP', 'FLANXP', 'FMARHDP', 'FMARHMP',
#        'FMARHWP', 'FMARHYP', 'FMIGP', 'FMILPP', 'FOCCP', 'FPAP', 'FPERNP',
#        'FPINCP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSEMP', 'FWAGP', 'FWKLP',
#        'FWKWP', 'FWRKP', 'PWGTP1', 'PWGTP2', 'PWGTP6', 'PWGTP7',
#        'PWGTP11', 'PWGTP12', 'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16',
#        'PWGTP18', 'PWGTP19', 'PWGTP22', 'PWGTP27', 'PWGTP28', 'PWGTP29',
#        'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP41', 'PWGTP44', 'PWGTP45',
#        'PWGTP46', 'PWGTP49', 'PWGTP50', 'PWGTP53', 'PWGTP59', 'PWGTP60',
#        'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP67', 'PWGTP69', 'PWGTP70',
#        'PWGTP72', 'PWGTP73', 'PWGTP76', 'PWGTP78', 'PWGTP79'], inplace=True)
    
    return dataframe

### Functions to make data uniform

In [4]:
def paul_pipeline(df):
    df['CIT_STATUS'] = np.where(df['CIT'] != 5, 1, 0)
    df['BORN_CIT'] = np.where((df['CITWP'].isna()) & ((df['CIT'] != 4) & (df['CIT'] != 5)), 1, 0)
    conditions = [ (df['CIT_STATUS'] == 1),(df['CIT_STATUS'] == 0)]
    choices = [0,1]
    df['CITWP'] = np.select(conditions, choices, df['CITWP'] )
    conditions = [(df['AGEP'] < 15),((df['AGEP'] >= 15) & (df['COW'].isna()))]
    choices = [0,10]
    df['COW'] = np.select(conditions, choices, df['COW'] )
    conditions = [ (df['AGEP'] < 5)]
    choices = [0]
    df['DDRS'] = np.select(conditions, choices, df['DDRS'] )
    conditions = [ (df['AGEP'] < 5)]
    choices = [0]
    df['DPHY'] = np.select(conditions, choices, df['DPHY'] )
    conditions = [ (df['AGEP'] < 5)]
    choices = [0]
    df['DREM'] = np.select(conditions, choices, df['DREM'] )
    df['ENG'] = np.where(df['AGEP'] < 5, 1, df['ENG'])
    df['ENG'] = np.where(df['ENG'].isna(), 5, df['ENG'])
    conditions = [ (df['ESR'] == 3) & (df['JWMNP'].isna()),df['JWMNP'].isna()]
    choices = [0,201]
    df['JWMNP'] = np.select(conditions, choices, df['JWMNP'] )
    df['JWRIP'] = np.where(df['JWRIP'].isna(), 0, df['JWRIP'] )
    conditions = [ df['AGEP'] < 15,(df['ESR'] == 3) & (df['JWMNP'].isna())]
    choices = [0,13]
    df['JWTR'] = np.select(conditions, choices, df['JWTR'] )
    df['JWTR'] = np.where(df['JWTR'].isna(), 14, df['JWTR'] )
    df['MARHD'] = np.where(df['AGEP'] < 15, 0, df['MARHD'] )
    df['MARHD'] = np.where(df['MARHD'].isna(), 3, df['MARHD'] )
    df['MARHM'] = np.where(df['AGEP'] < 15, 0, df['MARHM'] )
    df['MARHM'] = np.where(df['MARHM'].isna(), 3, df['MARHM'] )
    df['MARHT'] = np.where(df['AGEP'] < 15, 0, df['MARHT'] )
    df['MARHT'] = np.where(df['MARHD'].isna(), 4, df['MARHD'] )
    df['MARHYP'] = np.where(df['AGEP'] < 15, 0, df['MARHYP'] )
    df['MARHYP'] = np.where(df['MARHYP'].isna(), 1, df['MARHYP'] )
    df['MIG'] = np.where(df['AGEP'] < 1, 0, df['MIG'] )
    df['MIL'] = np.where(df['AGEP'] < 17, 0, df['MIL'])
    conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
    choices = [2,3,4]
    df['MLPCD'] = np.select(conditions, choices, df['MLPCD'] )
    conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
    choices = [2,3,4]
    df['MLPE'] = np.select(conditions, choices, df['MLPE'] )
    conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
    choices = [2,3,4]
    df['MLPFG'] = np.select(conditions, choices, df['MLPFG'] )
    conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
    choices = [2,3,4]
    df['MLPH'] = np.select(conditions, choices, df['MLPH'] )
    conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
    choices = [2,3,4]
    df['MLPI'] = np.select(conditions, choices, df['MLPI'] )
    conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
    choices = [2,3,4]
    df['MLPJ'] = np.select(conditions, choices, df['MLPJ'] )
    conditions = [ df['AGEP'] < 17,(df['MIL'] == 4),(df['MIL'] == 3)]
    choices = [2,3,4]
    df['MLPK'] = np.select(conditions, choices, df['MLPK'] )
    conditions = [ df['AGEP'] < 16,(df['ESR'] != 3) & (df['ESR'].notna())]
    choices = [0,4]
    df['NWLK'] = np.select(conditions, choices, df['NWLK'] )
    df['NWLK'] = np.where(df['NWLK'].isna(), 5, df['NWLK'] )
    df['SCH'] = np.where(df['SCH'].isna(),0,df['SCH'])
    df['DECADE'] = np.where(df['BORN_CIT'] == 1, 0, df['DECADE'])
    df['ESP'] = np.where(df['ESP'].isna(),0,df['ESP'])
    conditions = [ df['ESR'] ==3,(df['ESR'] != 3) & (df['ESR'].notna()) & (df['ESR'] != 6)]
    choices = [0,4]
    df['JWDP'] = np.select(conditions, choices, df['JWDP'] )
    df['JWDP'] = np.where(df['JWDP'].isna(),0,df['JWDP'])
    df['MIGSP'] = np.where(df['AGEP'] < 1,0,df['ST'])
    df['MSP'] = np.where(df['AGEP'] < 15,0,df['MSP'])
    df['NOP'] = np.where(df['NOP'].isna(),0,df['NOP'])
    df['OC'] = np.where(df['OC'].isna(),0,df['OC'])
    df['OCCP'] = np.where(df['AGEP'] < 16,0,df['OCCP'])
    df['OCCP'] = np.where(df['OCCP'].isna(),1,df['OCCP'])
    df['RC'] = np.where(df['RC'].isna(),3,df['RC'])
    df['SCIENGP'] = np.where(df['SCIENGP'].isna(),0,df['SCIENGP'])
    df['VPS'] = np.where(df['AGEP'] < 17,0,df['VPS'])
    df['VPS'] = np.where((df['MIL'] !=1) |(df['MIL'] !=2) ,16,df['VPS'])
    df['PAP'] = np.where(df['PAP'].isna(),0,df['PAP'])
    df['SSP'] = np.where(df['SSP'].isna(),0,df['SSP'])
    df['WKHP'] = np.where(df['WKHP'].isna(),0,df['WKHP'])
    df['WAGP'] = np.where(df['WAGP'].isna(),0,df['WAGP'])
    df['PERNP'] = np.where(df['PERNP'].isna(),0,df['PERNP'])
    df['PINCP'] = np.where(df['PINCP'].isna(),0,df['PINCP'])
    df['PAP'] = np.where(df['PAP'].isna(),0,df['PAP'])
    df['SSP'] = np.where(df['SSP'].isna(),0,df['SSP'])
    df['WKHP'] = np.where(df['WKHP'].isna(),0,df['WKHP'])
    df['WAGP'] = np.where(df['WAGP'].isna(),0,df['WAGP'])
    df['PERNP'] = np.where(df['PERNP'].isna(),0,df['PERNP'])
    df['PINCP'] = np.where(df['PINCP'].isna(),0,df['PINCP'])
    

    return df

In [5]:
df_paul = paul_pipeline(df_paul)

In [6]:
df_paul.head()

,RT,SERIALNO,DIVISION,SPORDER,PUMA,REGION,ST,ADJINC,PWGTP,AGEP,CIT,CITWP,COW,DDRS,DEAR,DEYE,DOUT,DPHY,DRAT,DRATX,DREM,ENG,FER,GCL,GCM,GCR,HINS1,HINS2,HINS3,HINS4,HINS5,HINS6,HINS7,INTP,JWMNP,JWRIP,JWTR,LANX,MAR,MARHD,MARHM,MARHT,MARHW,MARHYP,MIG,MIL,MLPA,MLPB,MLPCD,MLPE,MLPFG,MLPH,MLPI,MLPJ,MLPK,NWAB,NWAV,NWLA,NWLK,NWRE,OIP,PAP,RELP,RETP,SCH,SCHG,SCHL,SEMP,SEX,SSIP,SSP,WAGP,WKHP,WKL,WKW,WRK,YOEP,ANC,ANC1P,ANC2P,DECADE,DIS,DRIVESP,ESP,ESR,FOD1P,FOD2P,HICOV,HISP,INDP,JWAP,JWDP,LANP,MIGPUMA,MIGSP,MSP,NAICSP,NATIVITY,NOP,OC,OCCP,PAOC,PERNP,PINCP,POBP,POVPIP,POWPUMA,POWSP,PRIVCOV,PUBCOV,QTRBIR,RAC1P,RAC2P,RAC3P,RACAIAN,RACASN,RACBLK,RACNH,RACNUM,RACPI,RACSOR,RACWHT,RC,SCIENGP,SCIENGRLP,SFN,SFR,SOCP,VPS,WAOB,FAGEP,FANCP,FCITP,FCITWP,FCOWP,FDDRSP,FDEARP,FDEYEP,FDISP,FDOUTP,FDPHYP,FDRATP,FDRATXP,FDREMP,FENGP,FESRP,FFERP,FFODP,FGCLP,FGCMP,FGCRP,FHICOVP,FHINS1P,FHINS2P,FHINS3C,FHINS3P,FHINS4C,FHINS4P,FHINS5C,FHINS5P,FHINS6P,FHINS7P,FHISP,FINDP,FINTP,FJWDP,FJWMNP,FJWRIP,FJWTRP,FLANP,FLANXP,FMARP,FMARHDP,FMARHMP,FMARHTP,FMARHWP,FMARHYP,FMIGP,FMIGSP,FMILPP,FMILSP,FOCCP,FOIP,FPAP,FPERNP,FPINCP,FPOBP,FPOWSP,FPRIVCOVP,FPUBCOVP,FRACP,FRELP,FRETP,FSCHGP,FSCHLP,FSCHP,FSEMP,FSEXP,FSSIP,FSSP,FWAGP,FWKHP,FWKLP,FWKWP,FWRKP,FYOEP,PWGTP1,PWGTP2,PWGTP3,PWGTP4,PWGTP5,PWGTP6,PWGTP7,PWGTP8,PWGTP9,PWGTP10,PWGTP11,PWGTP12,PWGTP13,PWGTP14,PWGTP15,PWGTP16,PWGTP17,PWGTP18,PWGTP19,PWGTP20,PWGTP21,PWGTP22,PWGTP23,PWGTP24,PWGTP25,PWGTP26,PWGTP27,PWGTP28,PWGTP29,PWGTP30,PWGTP31,PWGTP32,PWGTP33,PWGTP34,PWGTP35,PWGTP36,PWGTP37,PWGTP38,PWGTP39,PWGTP40,PWGTP41,PWGTP42,PWGTP43,PWGTP44,PWGTP45,PWGTP46,PWGTP47,PWGTP48,PWGTP49,PWGTP50,PWGTP51,PWGTP52,PWGTP53,PWGTP54,PWGTP55,PWGTP56,PWGTP57,PWGTP58,PWGTP59,PWGTP60,PWGTP61,PWGTP62,PWGTP63,PWGTP64,PWGTP65,PWGTP66,PWGTP67,PWGTP68,PWGTP69,PWGTP70,PWGTP71,PWGTP72,PWGTP73,PWGTP74,PWGTP75,PWGTP76,PWGTP77,PWGTP78,PWGTP79,PWGTP80,CIT_STATUS,BORN_CIT
0,P,2018GQ0000012,2,1.0,3802,1,36,1013097,145.0,26.0,5,1.0,2.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,1,1,2,2,2,2,2,0.0,201.0,0.0,14.0,1.0,5,3.0,3.0,3.0,NaN,1.0,1.0,4.0,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,5.0,3.0,4.0,3.0,0.0,0.0,17,0.0,3.0,16.0,21.0,0.0,2,0.0,0.0,5200.0,50.0,1.0,6.0,NaN,2017.0,1,26,999,8.0,2,NaN,0.0,6.0,2601.0,NaN,1,1,7890.0,NaN,0.0,1170.0,NaN,36,6.0,611M3,2,0.0,0.0,5110.0,NaN,5200.0,5200.0,109,NaN,NaN,NaN,1,2,4,1,1,1,0,0,0,0,1,0,0,1,3.0,1.0,2.0,NaN,NaN,433021,16.0,5,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,1,1,1,NaN,1,NaN,1,NaN,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,1,1,1,0,0,1,1,0,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,263.0,270.0,143.0,147.0,23.0,145.0,142.0,149.0,143.0,22.0,143.0,144.0,261.0,273.0,21.0,23.0,264.0,145.0,22.0,145.0,21.0,23.0,141.0,145.0,264.0,145.0,145.0,146.0,143.0,264.0,141.0,144.0,21.0,21.0,268.0,265.0,23.0,148.0,259.0,149.0,262.0,262.0,142.0,145.0,22.0,146.0,144.0,144.0,149.0,21.0,144.0,143.0,261.0,271.0,21.0,23.0,270.0,144.0,24.0,141.0,23.0,23.0,140.0,144.0,269.0,145.0,143.0,144.0,144.0,267.0,146.0,146.0,21.0,24.0,266.0,263.0,21.0,146.0,265.0,144.0,0,0
1,P,2018GQ0000040,2,1.0,2702,1,36,1013097,43.0,21.0,1,0.0,1.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,5.0,NaN,NaN,NaN,NaN,1,1,2,2,2,2,2,0.0,2.0,0.0,10.0,2.0,5,3.0,3.0,3.0,NaN,1.0,3.0,4.0,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,5.0,3.0,4.0,3.0,0.0,0.0,17,0.0,2.0,15.0,20.0,0.0,1,0.0,0.0,1000.0,2.0,1.0,5.0,1.0,NaN,1,51,999,0.0,2,NaN,0.0,1.0,NaN,NaN,1,1,8680.0,283.0,4.0,NaN,3300.0,36,6.0,722Z,1,0.0,0.0,4110.0,NaN,1000.0,1000.0,36,NaN,2700.0,36.0,1,2,2,1,1,1,0,0,0,0,1,0,0,1,3.0,0.0,NaN,NaN,NaN,353031,16.0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,0,NaN,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80.0,43.0,77.0,41.0,40.0,76.0,43.0,7.0,77.0,75.0,6.0,40.0,40.0,7.0,41.0,7.0,44.0,43.0,40.0,6.0,76.0,40.0,76.0,40.0,40.0,79.0,43.0,5.0,80.0,76.0,4.0,43.0,41.0,7.0,40.0,6.0,41.0,42.0,41.0,6.0,80.0,41.0,74.0,41.0,43.0,77.0,43.0,6.0,78.0,74.0,7.0,41.0,41.0,6.0,40.0,7.0,43.0,43.0,42.0,6.0,77.0,43.0,76.0,40.0,40.0,78.0,43.0,6.0,77.0,77.0,6.0,42.0,43.0,7.0,40.0,6.0,43.0,40.0,42.0,6.0,1,1
2,P,2018GQ0000060,2,1.0,2001,1,36,1013097,88.0,18.0,2,0.0,1.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,2,2,2,1,2,2,2,0.0,201.0,0.0,14.0,1.0,5,3.0,3.0,3.0,NaN,1.0,3.0,4.0,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,5.0,2.0,4.0,2.0,0.0,0.0,17,0.0,2.0,15.0,16.0,0.0,2,0.0,0.0,0.0,0.0,2.0,NaN,2.0,2001.0,1,275,999,0.0,2,NaN,0.0,6.0,NaN,NaN,1,2,8680.0,NaN,0.0,1200.0,3700.0,36,6.0,722Z,1,0.0,0.0,4720.0,NaN,0.0,0.0,72,NaN,NaN,NaN,2,1,3,8,67,15,0,0,0,0,1,0,1,0,3.0,0.0,NaN,NaN,NaN,412010,16.0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0.0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,88.0,89.0,15.0,13.0,86.0,90.0,86.0,14.0,161.0,12.0,88.0,163.0,159.0,165.0,88.0,15.0,160.0,87.0,88.0,89.0,88.0,87.0,15.0,13.0,88.0,88.0,88.0,13.0,163.0,12.0,86.0,163.0,161.0,159.0,88.0,13.0,161.0,92.0,84.0,91.0,87.0,86.0,12.0,13.0,89.0,88.0,88.0,14.0,166.0,12.0,89.0,163.0,159.0,165.0,88.0,13.0,165.0,89.0,89.0,85.0,88.0,89.0,13.0,15.0,88.0,88.0,86.0,12.0,163.0,13.0,88.0,163.0,161.0,162.0,87.0,12.0,162.0,88.0,87.0,88.0,1,1
3,P,2018GQ0000081,2,1.0,2401,1,36,1013097,109.0,85.0,1,0.0,10.0,1.0,1,2,2.0,1.0,NaN,NaN,1.0,5.0,NaN,2.0,NaN,NaN,1,2,1,1,2,2,2,0.0,201.0,0.0,14.0,2.0,2,2.0,2.0,2.0,2.0,1950.0,1.0,4.0,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,5.0,3.0,4.0,3.0,0.0,0.0,16,0.0,1.0,NaN,16.0,0.0,2,0.0,13700.0,0.0,0.0,3.0,NaN,NaN,NaN,4,999,999,0.0,1,NaN,0.0,6.0,NaN,NaN,1,1,NaN,NaN,0.0,NaN,NaN,36,3.0,NaN,1,0.0,0.0,1.0,NaN,0.0,13700.0,36,NaN,NaN,NaN,1,1,3,1,1,1,0,0,0,0,1,0,0,1,3.0,0.0,NaN,NaN,NaN,NaN,16.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0,0.0,0,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,107.0,17.0,196.0,112.0,112.0,111.0,210.0,108.0,18.0,108.0,200.0,195.0,106.0,109.0,200.0,17.0,106.0,15.0,18.0,105.0,108.0,17.0,203.0,107.0,105.0,109.0,202.0,111.0,18.0,107.0,205.0,196.0,102.0,108.0,202.0,17.0,107.0,17.0,17.0,112.0,110.0,197.0,15.0,104.0,108.0,107.0,17.0,111.0,203.0,107.0,18.0,15.0,109.0,109.0,15.0,196.0,109.0,191.0,205.0,107.0,108.0,191.0,16.0,111.0,109.0,110.0,15.0,109.0,199.0,110.0,17.0,15.0,111.0,107.0,17.0,196.0,109.0,200.0,198.0,111.0,1,1
4,P,2018GQ0000103,2,1.0,1400,1,36,1013097,83.0,19.0,1,0.0,1.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,5.0,2.0,NaN,NaN,NaN,2,1,2,2,2,2,2,0.0,5.0,5.0,1.0,2.0,5,3.0,3.0,3.0,NaN,1.0,1.0,4.0,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,5.0,3.0,4.0,3.0,0.0,0.0,17,0.0,3.0,15.0,19.0,0.0,2,0.0,0.0,870.0,4.0,1.0,5.0,1.0,NaN,2,50,425,0.0,2,5.0,0.0,1.0,NaN,NaN,1,1,8590.0,181.0,4.0,NaN,NaN,36,6.0,713Z,1,0.0,0.0,2723.0,NaN,870.0,870.0,36,NaN,1400.0,36.0,1,2,4,1,1,1,0,0,0,0,1,0,0,1,3.0,0.0,NaN,NaN,NaN,272023,16.0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,82.0,12.0,151.0,83.0,12.0,10.0,83.0,85.0,82.0,84.0,83.0,152.0,81.0,13.0,154.0,82.0,149.0,83.0,13.0,153.0,83.0,12.0,149.0,83.0,13.0,13.0,83.0,84.0,82.0,81.0,81.0,152.0,83.0,11.0,154.0,83.0,151.0,85.0,13.0,13.0,81.0,151.0,13.0,81.0,153.0,154.0,81.0,80.0,86.0,80.0,82.0,13.0,80.0,155.0,12.0,83.0,10.0,84.0,153.0,10.0,83.0,154.0,10.0,84.0,153.0,153.0,81.0,82.0,83.0,82.0,81.0,12.0,80.0,154.0,12.0,80.0,12.0,83.0,152.0,154.0,1,1

In [7]:
df_paul.shape

(196967, 288)

In [8]:
def transform_INDP(df_):
    """
    Aggregating INDP categories
    """
    dataframe = df_.copy()
    dataframe['INDP'].fillna('None', inplace=True)
    dataframe['INDP'] = dataframe['INDP'].astype('str')
    conditions = [
        dataframe['INDP'].str.startswith('01'),
        dataframe['INDP'].str.startswith('02'),
        dataframe['INDP'].str.startswith('03'),
        dataframe['INDP'].str.startswith('04'),
        dataframe['INDP'].str.startswith('05'),
        dataframe['INDP'].str.startswith('06'),
        dataframe['INDP'].str.startswith('07'),
        dataframe['INDP'].str.startswith('10'),
        dataframe['INDP'].str.startswith('11'),
        dataframe['INDP'].str.startswith('12'),
        dataframe['INDP'].str.startswith('13'),
        dataframe['INDP'].str.startswith('14'),
        dataframe['INDP'].str.startswith('15'),
        dataframe['INDP'].str.startswith('16'),
        dataframe['INDP'].str.startswith('17'),
        dataframe['INDP'].str.startswith('18'),#16
        dataframe['INDP'].str.startswith('19'),
        dataframe['INDP'].str.startswith('20'),
        dataframe['INDP'].str.startswith('21'),
        dataframe['INDP'].str.startswith('22'),#20
        dataframe['INDP'].str.startswith('23'),
        dataframe['INDP'].str.startswith('24'),
        dataframe['INDP'].str.startswith('25'),
        dataframe['INDP'].str.startswith('26'),
        dataframe['INDP'].str.startswith('27'),
        dataframe['INDP'].str.startswith('28'),
        dataframe['INDP'].str.startswith('29'),
        dataframe['INDP'].str.startswith('30'),#28
        dataframe['INDP'].str.startswith('31'),
        dataframe['INDP'].str.startswith('32'),
        dataframe['INDP'].str.startswith('33'),
        dataframe['INDP'].str.startswith('34'),
        dataframe['INDP'].str.startswith('35'),
        dataframe['INDP'].str.startswith('36'),
        dataframe['INDP'].str.startswith('37'),
        dataframe['INDP'].str.startswith('38'),
        dataframe['INDP'].str.startswith('39'),
        dataframe['INDP'].str.startswith('40'),#38
        dataframe['INDP'].str.startswith('41'),
        dataframe['INDP'].str.startswith('42'),#40
        dataframe['INDP'].str.startswith('43'),
        dataframe['INDP'].str.startswith('44'),
        dataframe['INDP'].str.startswith('45'),
        dataframe['INDP'].str.startswith('46'),
        dataframe['INDP'].str.startswith('47'),
        dataframe['INDP'].str.startswith('48'),
        dataframe['INDP'].str.startswith('49'),
        dataframe['INDP'].str.startswith('50'),
        dataframe['INDP'].str.startswith('51'),
        dataframe['INDP'].str.startswith('52'),
        dataframe['INDP'].str.startswith('53'),
        dataframe['INDP'].str.startswith('54'),
        dataframe['INDP'].str.startswith('55'),
        dataframe['INDP'].str.startswith('56'),
        dataframe['INDP'].str.startswith('57'),
        dataframe['INDP'].str.startswith('60'),
        dataframe['INDP'].str.startswith('61'),
        dataframe['INDP'].str.startswith('62'),
        dataframe['INDP'].str.startswith('63'),
        dataframe['INDP'].str.startswith('64'),#20
        dataframe['INDP'].str.startswith('65'),
        dataframe['INDP'].str.startswith('66'),
        dataframe['INDP'].str.startswith('67'),
        dataframe['INDP'].str.startswith('68'),
        dataframe['INDP'].str.startswith('69'),
        dataframe['INDP'].str.startswith('70'),
        dataframe['INDP'].str.startswith('71'),
        dataframe['INDP'].str.startswith('72'),
        dataframe['INDP'].str.startswith('73'),
        dataframe['INDP'].str.startswith('74'),
        dataframe['INDP'].str.startswith('75'),
        dataframe['INDP'].str.startswith('76'),
        dataframe['INDP'].str.startswith('77'),
        dataframe['INDP'].str.startswith('78'),
        dataframe['INDP'].str.startswith('79'),
        dataframe['INDP'].str.startswith('80'),
        dataframe['INDP'].str.startswith('81'),
        dataframe['INDP'].str.startswith('82'),
        dataframe['INDP'].str.startswith('83'),
        dataframe['INDP'].str.startswith('84'),#20
        dataframe['INDP'].str.startswith('85'),
        dataframe['INDP'].str.startswith('86'),
        dataframe['INDP'].str.startswith('87'),
        dataframe['INDP'].str.startswith('88'),
        dataframe['INDP'].str.startswith('89'),
        dataframe['INDP'].str.startswith('90'),
        dataframe['INDP'].str.startswith('91'),
        dataframe['INDP'].str.startswith('92'),
        dataframe['INDP'].str.startswith('93'),
        dataframe['INDP'].str.startswith('94'),
        dataframe['INDP'].str.startswith('95'),
        dataframe['INDP'].str.startswith('96'),
        dataframe['INDP'].str.startswith('97'),
        dataframe['INDP'].str.startswith('98'),
        dataframe['INDP'].str.startswith('99'),#15
    ]
    choices = [
        'AGR1',
        'AGR2',
        'EXT1',
        'EXT2',
        'UTL1',
        'UTL2',
        'CON',
        'MFG1',
        'MFG2',
        'MFG3',
        'MFG4',
        'MFG5',
        'MFG6',
        'MFG7',
        'MFG8',
        'MFG9',#16
        'MFG10',
        'MFG11',
        'MFG12',
        'MFG13',#20
        'MFG14',
        'MFG15',
        'MFG16',
        'MFG17',
        'MFG18',
        'MFG19',
        'MFG20',
        'MFG21',#28
        'MFG22',
        'MFG23',
        'MFG24',
        'MFG25',
        'MFG26',
        'MFG27',
        'MFG28',
        'MFG29',
        'MFG30',
        'WHL1',
        'WHL2',
        'WHL3',#20
        'WHL4',
        'WHL5',
        'WHL6',
        'RET1',
        'RET2',
        'RET3',
        'RET4',
        'RET5',
        'RET6',
        'RET7',
        'RET8',
        'RET9',
        'RET10',
        'RET11',
        'RET12',
        'TRN1',
        'TRN2',
        'TRN3',
        'TRN4',
        'INF1',#20
        'INF2',
        'INF3',
        'INF4',
        'FIN1',
        'FIN2',
        'FIN3',
        'FIN4',
        'PRF1',
        'PRF2',
        'PRF3',
        'PRF4',
        'PRF5',
        'PRF6',
        'EDU',
        'MED1',
        'MED2',
        'MED3',
        'MED4',
        'SCA1',
        'SCA2',#20
        'ENT1',
        'ENT2',
        'SRV1',
        'SRV2',
        'SRV3',
        'SRV4',
        'SRV5',
        'SRV6',
        'ADM1',
        'ADM2',
        'ADM3',
        'MIL1',
        'MIL2',
        'MIL3',
        'None'#15
         
    ]
    
    dataframe['INDP'] = np.select(conditions,choices, 'None')
    
    return dataframe

In [9]:
df_paul = transform_INDP(df_paul)

In [10]:
df_paul.shape

(196967, 288)

In [11]:
def alberts_turn(df_):
    """
    'DIVISION', 'REGION', 'ST', 'AGE', 'CITIZEN', 'DEYE', 'DIS_ALONE',
       'DIS_VETP', 'DIS_VET', 'FER', 'GCM', 'GCR', 'MEDCAID', 'TRICARE',
       'HI_VA', 'INTP', 'LANX', 'MAR', 'MARHW', 'MIL', 'MLPA', 'NWAB',
       'NWAV', 'NWLA', 'OIP', 'RETP', 'SCHG', 'SCHL', 'SEMP', 'SEX',
       'SSIP', 'WKL', 'WKW', 'WRK', 'YR_ENTER_US', 'ANC', 'ANCES1',
       'ANC2P', 'DRIVESP', 'ESR', 'DEGREE1', 'DEGREE2', 'WK_ARR_TME',
       'LAN_HOME', 'MIGPUMA', 'NAICSP', 'NATIVITY', 'PAOC', 'POBP',
       'POWSP', 'PRIVCOV', 'PUBCOV', 'RAC1P', 'RAC2P', 'RAC3P', 'RACAIAN',
       'RACASN', 'RACBLK', 'RACNH', 'RACNUM', 'RACPI', 'RACSOR',
       'SCIENGRLP', 'SFN', 'SFR', 'SOCP', 'FCITP', 'FDEYEP', 'FDOUTP',
       'FDPHYP', 'FDREMP', 'FENGP', 'FFERP', 'FFODP', 'FGCLP', 'FHINS1P',
       'FHINS3C', 'FHINS3P', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FINTP',
       'FJWDP', 'FJWRIP', 'FJWTRP', 'FLANXP', 'FMARHDP', 'FMARHMP',
       'FMARHWP', 'FMARHYP', 'FMIGP', 'FMILPP', 'FOCCP', 'FPAP', 'FPERNP',
       'FPINCP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSEMP', 'FWAGP', 'FWKLP',
       'FWKWP', 'FWRKP', 'PWGTP1', 'PWGTP2', 'PWGTP6', 'PWGTP7',
       'PWGTP11', 'PWGTP12', 'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16',
       'PWGTP18', 'PWGTP19', 'PWGTP22', 'PWGTP27', 'PWGTP28', 'PWGTP29',
       'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP41', 'PWGTP44', 'PWGTP45',
       'PWGTP46', 'PWGTP49', 'PWGTP50', 'PWGTP53', 'PWGTP59', 'PWGTP60',
       'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP67', 'PWGTP69', 'PWGTP70',
       'PWGTP72', 'PWGTP73', 'PWGTP76', 'PWGTP78', 'PWGTP79'
       
    """
    dataframe = df_.copy()
    # DIVISION
    # dataframe.drop(columns=['DIVISION'], inplace=True)
    
    # REGION
    # dataframe.drop(columns=['REGION'], inplace=True)
    
    # ST
    # dataframe.drop(columns=['ST'], inplace=True)
    
    # AGE
    # Keep AGE as is dataframe['AGEP']
    
    # CITIZEN
    # Keep CITIZEN as is dataframe['CIT']
    
    # DEYE
    # Keep DEYE as is dataframe['DEYE']
    
    # DIS_ALONE
    conditions = [dataframe['DOUT'].eq(1), dataframe['DOUT'].eq(2)]
    choices = ['Yes', 'No']
    
    dataframe['DOUT_cat'] = np.select(conditions, choices, 'LT_15yrs')
    
    # DIS_VETP
    # dataframe.drop(columns=['DRAT'], inplace=True)
    
    # DIS_VET
    # dataframe.drop(columns=['DRATX'], inplace=True)
    
    # FER
    conditions = [dataframe['FER'].eq(1), dataframe['FER'].eq(2)]
    choices = ['Yes', 'No']
    
    dataframe['FER_cat'] = np.select(conditions, choices, 'Not_Applicable')
    conditions = [ dataframe['AGEP'] < 17,(dataframe['MIL'] == 4),(dataframe['MIL'] == 3)]
    choices = [2,3,4]
    dataframe['MLPA'] = np.select(conditions, choices, dataframe['MLPA'] )
    # GCM
    # dataframe.drop(columns=['GCM'], inplace=True)
    
    # MEDCAID
    # dataframe.drop(columns=['HINS3'], inplace=True)
    
    # TRICARE
    # dataframe.drop(columns=['HINS5'], inplace=True)
    
    # HI_VA
    # dataframe.drop(columns=['HINS6'], inplace=True)
    
    # INTP
    dataframe['INTP_cat'] = np.where(dataframe['INTP'].isna(), 0, dataframe['INTP'])
    
    # LANX
    conditions = [dataframe['LANX'].eq(1), dataframe['LANX'].eq(2)]
    choices = ['Other_Lang', 'English_Lang']
    
    dataframe['LANX_cat'] = np.select(conditions, choices, 'Baby_Lang')
    
    # MAR
    # Keep MAR as is dataframe['MAR']
    
    # MARHW
    dataframe['MARHW_cat'] = np.where(dataframe['MARHW'].isna(), 'Unknown', dataframe['MARHW'])
    

    
    # MIL
    conditions = [dataframe['MIL'].eq(1), dataframe['MIL'].eq(2), dataframe['MIL'].eq(3), dataframe['MIL'].eq(4)]
    choices = ['Cur_Active', 'Past_Active', 'Cond_Active', 'Never_Served']
    
    dataframe['MIL_cat'] = np.select(conditions, choices, 'LT_17yrold')
    
    # MLPA
    conditions = [dataframe['MLPA'].eq(0), dataframe['MLPA'].eq(1)]
    choices = ['No_Served', 'Yes_Served']
    
    dataframe['MLPA_cat'] = np.select(conditions, choices, 'LT_17yrold')
    
    # OIP
    dataframe['OIP_cat'] = np.where(dataframe['OIP'].isna(), 0, dataframe['OIP'])
    
    # RETP
    dataframe['RETP_cat'] = np.where(dataframe['RETP'].isna(), 0 , dataframe['RETP'])
    
    # SCHG
    conditions = [
        dataframe['SCHG'].eq(1), dataframe['SCHG'].eq(2), dataframe['SCHG'].eq(3), dataframe['SCHG'].eq(4), 
        dataframe['SCHG'].eq(5), dataframe['SCHG'].eq(6), dataframe['SCHG'].eq(7), dataframe['SCHG'].eq(8), 
        dataframe['SCHG'].eq(9), dataframe['SCHG'].eq(10), dataframe['SCHG'].eq(11), dataframe['SCHG'].eq(12),
        dataframe['SCHG'].eq(13), dataframe['SCHG'].eq(14), dataframe['SCHG'].eq(15), dataframe['SCHG'].eq(16)
    ]
    choices = [
        'Nursery', 'Kindergarten', 'Grade_1', 'Grade_2',
        'Grade_3', 'Grade_4', 'Grade_5', 'Grade_6',
        'Grade_7', 'Grade_8', 'Grade_9', 'Grade_10',
        'Grade_11', 'Grade_12', 'Undergrad', 'Graduate'
    ]
    
    dataframe['SCHG_cat'] = np.select(conditions,choices, 'Not_Attending')
    
    # SCHL
    conditions = [
        dataframe['SCHL'].eq(1), dataframe['SCHL'].eq(2), dataframe['SCHL'].eq(3), dataframe['SCHL'].eq(4), 
        dataframe['SCHL'].eq(5), dataframe['SCHL'].eq(6), dataframe['SCHL'].eq(7), dataframe['SCHL'].eq(8), 
        dataframe['SCHL'].eq(9), dataframe['SCHL'].eq(10), dataframe['SCHL'].eq(11), dataframe['SCHL'].eq(12),
        dataframe['SCHL'].eq(13), dataframe['SCHL'].eq(14), dataframe['SCHL'].eq(15), dataframe['SCHL'].eq(16),
        dataframe['SCHL'].eq(17), dataframe['SCHL'].eq(18), dataframe['SCHL'].eq(19), dataframe['SCHL'].eq(20),
        dataframe['SCHL'].eq(21), dataframe['SCHL'].eq(22), dataframe['SCHL'].eq(23), dataframe['SCHL'].eq(24)
    ]
    choices = [
        'No_School', 'Nursery', 'Kindergarten', 'Grade_1', 
        'Grade_2', 'Grade_3', 'Grade_4', 'Grade_5', 
        'Grade_6', 'Grade_7', 'Grade_8', 'Grade_9', 
        'Grade_10', 'Grade_11', 'Grade_12', 'HS_Diploma', 
        'GED_alt', 'LT1_College', 'NoDegree_College','Associates', 
        ' Bachelors', 'Masters', 'Professional', 'Doctorate'
        
    ]
    
    dataframe['SCHL_cat'] = np.select(conditions, choices, 'LT_3yrold')
    
    # SEMP
    dataframe['SEMP_cat'] = np.where(dataframe['SEMP'].isna(), 0, dataframe['SEMP'])
    
    # SEX
    # Keep SEX as is dataframe['SEX']
    
    # SSIP
    dataframe['SSIP_cat'] = np.where(dataframe['SSIP'].isna(), 0 , dataframe['SSIP'])
    
    # WKL
    conditions = [dataframe['WKL'].eq(1), dataframe['WKL'].eq(2), dataframe['WKL'].eq(3)]
    choices = ['LT1', 'BT1_5', 'GT5']
    
    dataframe['WKL_cat'] = np.select(conditions, choices, 'LT_16yrsold')
    
    # WKW
    conditions = [
        dataframe['WKW'].eq(1), dataframe['WKW'].eq(2), dataframe['WKW'].eq(3),
        dataframe['WKW'].eq(4), dataframe['WKW'].eq(5), dataframe['WKW'].eq(6)
    ]
    choices = [
        '50_52wks', '48_49wks', '40_47wks',
        '27_39wks', '14_26wks', 'LT_14wks'
    ]
    
    dataframe['WKW_cat'] = np.select(conditions, choices, 'Not_Worked')
    
    # WRK
    conditions = [dataframe['WRK'].eq(1), dataframe['WRK'].eq(2)]
    choices = ['Worked', 'Not_Worked']
    
    dataframe['WRK_cat'] = np.select(conditions, choices, 'Not_Reported')
    
    # YR_ENTER_US
    conditions = [
        dataframe['YOEP'].lt(1949.1), 
        dataframe['YOEP'].lt(1959.1) & dataframe['YOEP'].gt(1949.9),
        dataframe['YOEP'].lt(1969.1) & dataframe['YOEP'].gt(1959.9),
        dataframe['YOEP'].lt(1979.1) & dataframe['YOEP'].gt(1969.9),
        dataframe['YOEP'].lt(1989.1) & dataframe['YOEP'].gt(1979.9),
        dataframe['YOEP'].lt(1999.1) & dataframe['YOEP'].gt(1989.9),
        dataframe['YOEP'].lt(2009.1) & dataframe['YOEP'].gt(1999.9),
        dataframe['YOEP'].lt(2019.1) & dataframe['YOEP'].gt(2009.9),
        dataframe['YOEP'].isna()
    ]
    choices = [
        'Below_50s',
        'Immigr_50s',
        'Immigr_60s',
        'Immigr_70s',
        'Immigr_80s',
        'Immigr_90s',
        'Immigr_00s',
        'Immigr_10s',
        'Naturalized'
    ]
    
    dataframe['YOEP_cat'] = np.select(conditions,choices, 'Unknown')
    
    # ANC
    # Keep ANC as is dataframe['ANC']
    
    # ANCES1
    # Keep ANCES1 as is dataframe['ANC1P']
    
    # ANC2P
    # Keep ANC2P as is dataframe['ANC2P']
    
    
    # DRIVESP
    conditions = [dataframe['DRIVESP'].eq(1), dataframe['DRIVESP'].eq(2), dataframe['DRIVESP'].eq(3),
                 dataframe['DRIVESP'].eq(4), dataframe['DRIVESP'].eq(5), dataframe['DRIVESP'].eq(6)]
    choices = ['1_driver', '2_driver', '3_driver',
              '4_driver', '5_6_driver', 'GT7_driver']
    
    dataframe['DRIVESP_cat'] = np.select(conditions, choices, 'No_Drive')
    

    
    # ESR
    conditions = [dataframe['ESR'].eq(1), dataframe['ESR'].eq(2), dataframe['ESR'].eq(3),
                 dataframe['ESR'].eq(4), dataframe['ESR'].eq(5), dataframe['ESR'].eq(6)]
    choices = ['Employed_at_work', 'Employed_not_work', 'Unemployed',
              'ArmedForces_at_work', 'ArmedForces_not_work', 'Not_Labor']
    
    dataframe['ESR_cat'] = np.select(conditions, choices, 'LT_16yrsold')
    
    # DEGREE1
    # dataframe.drop(columns=['FOD1P'], inplace=True)
    
    # DEGREE2
    # dataframe.drop(columns=['FOD2P'], inplace=True)
    
    # WK_ARR_TME
    # Keep WK_ARR_TIME as is dataframe['JWAP']
    
    # LAN_HOME
    # dataframe.drop(columns=['LANP'], inplace=True)
    
    # MIGPUMA
    # dataframe.drop(columns=['MIGPUMA'], inplace=True)
    
    # NAICSP
    dataframe['NAICSP'].fillna('None', inplace=True)
    conditions = [
        dataframe['NAICSP'].str.startswith('11'),
        dataframe['NAICSP'].str.startswith('21'),
        dataframe['NAICSP'].str.startswith('22'),
        dataframe['NAICSP'].str.startswith('23'),
        dataframe['NAICSP'].str.startswith('31'),
        dataframe['NAICSP'].str.startswith('32'),
        dataframe['NAICSP'].str.startswith('33'),
        dataframe['NAICSP'].str.startswith('3M'),
        dataframe['NAICSP'].str.startswith('42'),
        dataframe['NAICSP'].str.startswith('44'),
        dataframe['NAICSP'].str.startswith('45'),
        dataframe['NAICSP'].str.startswith('4M'),
        dataframe['NAICSP'].str.startswith('51'),
        dataframe['NAICSP'].str.startswith('52'),
        dataframe['NAICSP'].str.startswith('53'),
        dataframe['NAICSP'].str.startswith('54'),
        dataframe['NAICSP'].str.startswith('55'),
        dataframe['NAICSP'].str.startswith('56'),
        dataframe['NAICSP'].str.startswith('61'),
        dataframe['NAICSP'].str.startswith('62'),
        dataframe['NAICSP'].str.startswith('71'),
        dataframe['NAICSP'].str.startswith('72'),
        dataframe['NAICSP'].str.startswith('81'),
        dataframe['NAICSP'].str.startswith('92'),
        dataframe['NAICSP'].str.startswith('99'),
    ]
    choices = [
        'AGR',
        'EXT',
        'UTL',
        'CON',
        'MFG1',
        'MFG2',
        'MFG3',
        'MFG3',
        'WHL',
        'RET1',
        'RET2',
        'RET2',
        'INF',
        'FIN1',
        'FIN2',
        'PRF1',
        'PRF2',
        'PRF3',
        'EDU',
        'MED',
        'ENT1',
        'ENT2',
        'SRV',
        'ADM',
        'No_Work'
    ]
    
    dataframe['NAICSP_cat'] = np.select(conditions, choices, 'No_Work')
    
    # NATIVITY
    # Keep NATIVITY as is dataframe['NATIVITY']
    
    # PAOC
    # dataframe.drop(columns=['PAOC'], inplace=True)
    

    # POBP
    dataframe['POBP_cat'] = np.where(dataframe['POBP'].eq(36), 1, 0)
    
    
    # POWSP
    dataframe['POWSP_cat'] = np.where(dataframe['POWSP'].eq(36), 1, 0)
    
    # PRIVCOV
    # dataframe.drop(columns=['PRIVCOV'], inplace=True)
    
    # PUBCOV
    # dataframe.drop(columns=['PUBCOV'], inplace=True)
    
    # RAC1P
    conditions = [
        dataframe['RAC1P'].eq(1), dataframe['RAC1P'].eq(2), dataframe['RAC1P'].eq(3),
        dataframe['RAC1P'].eq(4), dataframe['RAC1P'].eq(5), dataframe['RAC1P'].eq(6),
        dataframe['RAC1P'].eq(7), dataframe['RAC1P'].eq(8), dataframe['RAC1P'].eq(9),
    ]
    choices = [
        'White', 'Black', 'American_Indian',
        'Alaska_Native', 'American_Indian',' Asian',
        'Native_Hawaii', 'Some_Other', 'GT2_race'
    ]
    
    dataframe['RAC1P_cat'] = np.select(conditions, choices, 'Unknown')
    
    # RAC2P
    # dataframe.drop(columns=['RAC2P'], inplace=True)
    
    # RAC3P
    # dataframe.drop(columns=['RAC3P'], inplace=True)
    
    # RACAIAN
    # Keep as is
    
    # RACASN
    # Keep as is
    
    # RACBLK
    # Keep as is
    
    # RACNH
    # Keep as is
    
    # RACNUM
    # Keep as is
    
    # RACPI
    # Keep as is
    
    # RACSOR
    # Keep as is
    
    # SCIENGRLP
    conditions = [dataframe['SCIENGRLP'].eq(1), dataframe['SCIENGRLP'].eq(2)]
    choices = ['Yes', 'No']
    
    dataframe['SCIENGRLP_cat'] = np.select(conditions, choices, 'LT_Bachelors')
    
    # SFN
    # dataframe.drop(columns = ['SFN'], inplace=True)
    
    # SFR
    # dataframe.drop(columns=['SFR'], inplace=True)
    
    # SOCP
    
    dataframe['SOCP'].fillna('None', inplace=True)
    conditions = [
        dataframe['SOCP'].str.startswith('111'),
        dataframe['SOCP'].str.startswith('112'),
        dataframe['SOCP'].str.startswith('113'),
        dataframe['SOCP'].str.startswith('119'),
        dataframe['SOCP'].str.startswith('131'),
        dataframe['SOCP'].str.startswith('132'),
        dataframe['SOCP'].str.startswith('151'),
        dataframe['SOCP'].str.startswith('152'),
        dataframe['SOCP'].str.startswith('171'),
        dataframe['SOCP'].str.startswith('172'),
        dataframe['SOCP'].str.startswith('173'),
        dataframe['SOCP'].str.startswith('191'),
        dataframe['SOCP'].str.startswith('192'),
        dataframe['SOCP'].str.startswith('193'),
        dataframe['SOCP'].str.startswith('194'),
        dataframe['SOCP'].str.startswith('195'),
        dataframe['SOCP'].str.startswith('211'),
        dataframe['SOCP'].str.startswith('212'),
        dataframe['SOCP'].str.startswith('231'),
        dataframe['SOCP'].str.startswith('232'),#20
        dataframe['SOCP'].str.startswith('251'),
        dataframe['SOCP'].str.startswith('252'),
        dataframe['SOCP'].str.startswith('253'),
        dataframe['SOCP'].str.startswith('254'),
        dataframe['SOCP'].str.startswith('259'),
        dataframe['SOCP'].str.startswith('271'),
        dataframe['SOCP'].str.startswith('272'),
        dataframe['SOCP'].str.startswith('273'),
        dataframe['SOCP'].str.startswith('274'),
        dataframe['SOCP'].str.startswith('291'),
        dataframe['SOCP'].str.startswith('292'),
        dataframe['SOCP'].str.startswith('299'),
        dataframe['SOCP'].str.startswith('311'),
        dataframe['SOCP'].str.startswith('312'),
        dataframe['SOCP'].str.startswith('319'),
        dataframe['SOCP'].str.startswith('331'),
        dataframe['SOCP'].str.startswith('332'),
        dataframe['SOCP'].str.startswith('333'),
        dataframe['SOCP'].str.startswith('339'),
        dataframe['SOCP'].str.startswith('351'),#20
        dataframe['SOCP'].str.startswith('352'),
        dataframe['SOCP'].str.startswith('353'),
        dataframe['SOCP'].str.startswith('359'),
        dataframe['SOCP'].str.startswith('371'),
        dataframe['SOCP'].str.startswith('372'),
        dataframe['SOCP'].str.startswith('373'),
        dataframe['SOCP'].str.startswith('391'),
        dataframe['SOCP'].str.startswith('392'),
        dataframe['SOCP'].str.startswith('393'),
        dataframe['SOCP'].str.startswith('394'),
        dataframe['SOCP'].str.startswith('395'),
        dataframe['SOCP'].str.startswith('396'),
        dataframe['SOCP'].str.startswith('397'),
        dataframe['SOCP'].str.startswith('399'),
        dataframe['SOCP'].str.startswith('411'),
        dataframe['SOCP'].str.startswith('412'),
        dataframe['SOCP'].str.startswith('413'),
        dataframe['SOCP'].str.startswith('414'),
        dataframe['SOCP'].str.startswith('419'),
        dataframe['SOCP'].str.startswith('431'),#20
        dataframe['SOCP'].str.startswith('432'),
        dataframe['SOCP'].str.startswith('433'),
        dataframe['SOCP'].str.startswith('434'),
        dataframe['SOCP'].str.startswith('435'),
        dataframe['SOCP'].str.startswith('436'),
        dataframe['SOCP'].str.startswith('439'),
        dataframe['SOCP'].str.startswith('451'),
        dataframe['SOCP'].str.startswith('452'),
        dataframe['SOCP'].str.startswith('453'),
        dataframe['SOCP'].str.startswith('454'),
        dataframe['SOCP'].str.startswith('471'),
        dataframe['SOCP'].str.startswith('472'),
        dataframe['SOCP'].str.startswith('473'),
        dataframe['SOCP'].str.startswith('474'),
        dataframe['SOCP'].str.startswith('475'),
        dataframe['SOCP'].str.startswith('491'),
        dataframe['SOCP'].str.startswith('492'),
        dataframe['SOCP'].str.startswith('493'),
        dataframe['SOCP'].str.startswith('499'),
        dataframe['SOCP'].str.startswith('511'),#20
        dataframe['SOCP'].str.startswith('512'),
        dataframe['SOCP'].str.startswith('513'),
        dataframe['SOCP'].str.startswith('514'),
        dataframe['SOCP'].str.startswith('515'),
        dataframe['SOCP'].str.startswith('516'),
        dataframe['SOCP'].str.startswith('517'),
        dataframe['SOCP'].str.startswith('518'),
        dataframe['SOCP'].str.startswith('519'),
        dataframe['SOCP'].str.startswith('531'),
        dataframe['SOCP'].str.startswith('532'),
        dataframe['SOCP'].str.startswith('533'),
        dataframe['SOCP'].str.startswith('534'),
        dataframe['SOCP'].str.startswith('535'),
        dataframe['SOCP'].str.startswith('536'),
        dataframe['SOCP'].str.startswith('537'),
        dataframe['SOCP'].str.startswith('551'),
        dataframe['SOCP'].str.startswith('552'),
        dataframe['SOCP'].str.startswith('553'),
        dataframe['SOCP'].str.startswith('559'),
        dataframe['SOCP'].str.startswith('999'),#20
    ]
    choices = [
        'MGR1',
        'MGR2',
        'MGR3',
        'MGR4',
        'BUS1',
        'FIN1',
        'CMM1',
        'CMM2',
        'ENG1',
        'ENG2',
        'ENG3',
        'SCI1',
        'SCI2',
        'SCI3',
        'SCI4',
        'SCI5',
        'CMS1',
        'CMS2',
        'LGL1',
        'LGL2',#20
        'EDU1',
        'EDU2',
        'EDU3',
        'EDU4',
        'EDU5',
        'ENT1',
        'ENT2',
        'ENT3',
        'ENT4',
        'MED1',
        'MED2',
        'MED3',
        'HLS1',
        'HLS2',
        'HLS3',
        'PRT1',
        'PRT2',
        'PRT3',
        'PRT4',
        'EAT1',#20
        'EAT2',
        'EAT3',
        'EAT4',
        'CLN1',
        'CLN2',
        'CLN3',
        'PRS1',
        'PRS2',
        'PRS3',
        'PRS4',
        'PRS5',
        'PRS6',
        'PRS7',
        'PRS8',
        'SAL1',
        'SAL2',
        'SAL3',
        'SAL4',
        'SAL5',
        'OFF1',#20
        'OFF2',
        'OFF3',
        'OFF4',
        'OFF5',
        'OFF6',
        'OFF7',
        'FFF1',
        'FFF2',
        'FFF3',
        'FFF4',
        'EXT1',
        'EXT2',
        'EXT3',
        'EXT4',
        'EXT5',
        'PPR1',
        'PPR2',
        'PPR3',
        'PPR4',
        'PRD1',#20
        'PRD2',
        'PRD3',
        'PRD4',
        'PRD5',
        'PRD6',
        'PRD7',
        'PRD8',
        'PRD9',
        'TRN1',
        'TRN2',
        'TRN3',
        'TRN4',
        'TRN5',
        'TRN6',
        'TRN7',
        'MIL1',
        'MIL2',
        'MIL3',
        'MIL4',
        'No_Work'
    ]
    
    dataframe['SOCP_cat'] = np.select(conditions, choices, 'No_Work')
    
    #drop all flags and weights
#     dataframe.drop(columns =['FCITP', 'FDEYEP', 'FDOUTP',
#        'FDPHYP', 'FDREMP', 'FENGP', 'FFERP', 'FFODP', 'FGCLP', 'FHINS1P',
#        'FHINS3C', 'FHINS3P', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FINTP',
#        'FJWDP', 'FJWRIP', 'FJWTRP', 'FLANXP', 'FMARHDP', 'FMARHMP',
#        'FMARHWP', 'FMARHYP', 'FMIGP', 'FMILPP', 'FOCCP', 'FPAP', 'FPERNP',
#        'FPINCP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSEMP', 'FWAGP', 'FWKLP',
#        'FWKWP', 'FWRKP', 'PWGTP1', 'PWGTP2', 'PWGTP6', 'PWGTP7',
#        'PWGTP11', 'PWGTP12', 'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16',
#        'PWGTP18', 'PWGTP19', 'PWGTP22', 'PWGTP27', 'PWGTP28', 'PWGTP29',
#        'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP41', 'PWGTP44', 'PWGTP45',
#        'PWGTP46', 'PWGTP49', 'PWGTP50', 'PWGTP53', 'PWGTP59', 'PWGTP60',
#        'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP67', 'PWGTP69', 'PWGTP70',
#        'PWGTP72', 'PWGTP73', 'PWGTP76', 'PWGTP78', 'PWGTP79'], inplace=True)
    
    return dataframe

In [12]:
df_al = alberts_turn(df_al)

In [13]:
df_al.head()

,RT,SERIALNO,DIVISION,SPORDER,PUMA,REGION,ST,ADJINC,PWGTP,AGEP,CIT,CITWP,COW,DDRS,DEAR,DEYE,DOUT,DPHY,DRAT,DRATX,DREM,ENG,FER,GCL,GCM,GCR,HINS1,HINS2,HINS3,HINS4,HINS5,HINS6,HINS7,INTP,JWMNP,JWRIP,JWTR,LANX,MAR,MARHD,MARHM,MARHT,MARHW,MARHYP,MIG,MIL,MLPA,MLPB,MLPCD,MLPE,MLPFG,MLPH,MLPI,MLPJ,MLPK,NWAB,NWAV,NWLA,NWLK,NWRE,OIP,PAP,RELP,RETP,SCH,SCHG,SCHL,SEMP,SEX,SSIP,SSP,WAGP,WKHP,WKL,WKW,WRK,YOEP,ANC,ANC1P,ANC2P,DECADE,DIS,DRIVESP,ESP,ESR,FOD1P,FOD2P,HICOV,HISP,INDP,JWAP,JWDP,LANP,MIGPUMA,MIGSP,MSP,NAICSP,NATIVITY,NOP,OC,OCCP,PAOC,PERNP,PINCP,POBP,POVPIP,POWPUMA,POWSP,PRIVCOV,PUBCOV,QTRBIR,RAC1P,RAC2P,RAC3P,RACAIAN,RACASN,RACBLK,RACNH,RACNUM,RACPI,RACSOR,RACWHT,RC,SCIENGP,SCIENGRLP,SFN,SFR,SOCP,VPS,WAOB,FAGEP,FANCP,FCITP,FCITWP,FCOWP,FDDRSP,FDEARP,FDEYEP,FDISP,FDOUTP,FDPHYP,FDRATP,FDRATXP,FDREMP,FENGP,FESRP,FFERP,FFODP,FGCLP,FGCMP,FGCRP,FHICOVP,FHINS1P,FHINS2P,FHINS3C,FHINS3P,FHINS4C,FHINS4P,FHINS5C,FHINS5P,FHINS6P,FHINS7P,FHISP,FINDP,FINTP,FJWDP,FJWMNP,FJWRIP,FJWTRP,FLANP,FLANXP,FMARP,FMARHDP,FMARHMP,FMARHTP,FMARHWP,FMARHYP,FMIGP,FMIGSP,FMILPP,FMILSP,FOCCP,FOIP,FPAP,FPERNP,FPINCP,FPOBP,FPOWSP,FPRIVCOVP,FPUBCOVP,FRACP,FRELP,FRETP,FSCHGP,FSCHLP,FSCHP,FSEMP,FSEXP,FSSIP,FSSP,FWAGP,FWKHP,FWKLP,FWKWP,FWRKP,FYOEP,PWGTP1,PWGTP2,PWGTP3,PWGTP4,PWGTP5,PWGTP6,PWGTP7,PWGTP8,PWGTP9,PWGTP10,PWGTP11,PWGTP12,PWGTP13,PWGTP14,PWGTP15,PWGTP16,PWGTP17,PWGTP18,PWGTP19,PWGTP20,PWGTP21,PWGTP22,PWGTP23,PWGTP24,PWGTP25,PWGTP26,PWGTP27,PWGTP28,PWGTP29,PWGTP30,PWGTP31,PWGTP32,PWGTP33,PWGTP34,PWGTP35,PWGTP36,PWGTP37,PWGTP38,PWGTP39,PWGTP40,PWGTP41,PWGTP42,PWGTP43,PWGTP44,PWGTP45,PWGTP46,PWGTP47,PWGTP48,PWGTP49,PWGTP50,PWGTP51,PWGTP52,PWGTP53,PWGTP54,PWGTP55,PWGTP56,PWGTP57,PWGTP58,PWGTP59,PWGTP60,PWGTP61,PWGTP62,PWGTP63,PWGTP64,PWGTP65,PWGTP66,PWGTP67,PWGTP68,PWGTP69,PWGTP70,PWGTP71,PWGTP72,PWGTP73,PWGTP74,PWGTP75,PWGTP76,PWGTP77,PWGTP78,PWGTP79,PWGTP80,DOUT_cat,FER_cat,INTP_cat,LANX_cat,MARHW_cat,MIL_cat,MLPA_cat,OIP_cat,RETP_cat,SCHG_cat,SCHL_cat,SEMP_cat,SSIP_cat,WKL_cat,WKW_cat,WRK_cat,YOEP_cat,DRIVESP_cat,ESR_cat,NAICSP_cat,POBP_cat,POWSP_cat,RAC1P_cat,SCIENGRLP_cat,SOCP_cat
0,P,2018GQ0000012,2,1.0,3802,1,36,1013097,145.0,26.0,5,NaN,2.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,1,1,2,2,2,2,2,0.0,NaN,NaN,NaN,1.0,5,NaN,NaN,NaN,NaN,NaN,1.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,3.0,3.0,3.0,0.0,0.0,17,0.0,3.0,16.0,21.0,0.0,2,0.0,0.0,5200.0,50.0,1.0,6.0,NaN,2017.0,1,26,999,8.0,2,NaN,NaN,6.0,2601.0,NaN,1,1,7890.0,NaN,NaN,1170.0,NaN,NaN,6.0,611M3,2,NaN,NaN,5110.0,NaN,5200.0,5200.0,109,NaN,NaN,NaN,1,2,4,1,1,1,0,0,0,0,1,0,0,1,NaN,1.0,2.0,NaN,NaN,433021,NaN,5,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,1,1,1,NaN,1,NaN,1,NaN,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,1,1,1,0,0,1,1,0,0,1,0,0,0,1,0,1,1,1,1,1,1,0,0,263.0,270.0,143.0,147.0,23.0,145.0,142.0,149.0,143.0,22.0,143.0,144.0,261.0,273.0,21.0,23.0,264.0,145.0,22.0,145.0,21.0,23.0,141.0,145.0,264.0,145.0,145.0,146.0,143.0,264.0,141.0,144.0,21.0,21.0,268.0,265.0,23.0,148.0,259.0,149.0,262.0,262.0,142.0,145.0,22.0,146.0,144.0,144.0,149.0,21.0,144.0,143.0,261.0,271.0,21.0,23.0,270.0,144.0,24.0,141.0,23.0,23.0,140.0,144.0,269.0,145.0,143.0,144.0,144.0,267.0,146.0,146.0,21.0,24.0,266.0,263.0,21.0,146.0,265.0,144.0,No,No,0.0,Other_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Graduate,Bachelors,0.0,0.0,LT1,LT_14wks,Not_Reported,Immigr_10s,No_Drive,Not_Labor,EDU,0,0,White,No,OFF3
1,P,2018GQ0000040,2,1.0,2702,1,36,1013097,43.0,21.0,1,NaN,1.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1,1,2,2,2,2,2,0.0,2.0,NaN,10.0,2.0,5,NaN,NaN,NaN,NaN,NaN,3.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,3.0,3.0,3.0,0.0,0.0,17,0.0,2.0,15.0,20.0,0.0,1,0.0,0.0,1000.0,2.0,1.0,5.0,1.0,NaN,1,51,999,NaN,2,NaN,NaN,1.0,NaN,NaN,1,1,8680.0,283.0,150.0,NaN,3300.0,36.0,6.0,722Z,1,NaN,NaN,4110.0,NaN,1000.0,1000.0,36,NaN,2700.0,36.0,1,2,2,1,1,1,0,0,0,0,1,0,0,1,NaN,NaN,NaN,NaN,NaN,353031,NaN,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,0,NaN,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,80.0,43.0,77.0,41.0,40.0,76.0,43.0,7.0,77.0,75.0,6.0,40.0,40.0,7.0,41.0,7.0,44.0,43.0,40.0,6.0,76.0,40.0,76.0,40.0,40.0,79.0,43.0,5.0,80.0,76.0,4.0,43.0,41.0,7.0,40.0,6.0,41.0,42.0,41.0,6.0,80.0,41.0,74.0,41.0,43.0,77.0,43.0,6.0,78.0,74.0,7.0,41.0,41.0,6.0,40.0,7.0,43.0,43.0,42.0,6.0,77.0,43.0,76.0,40.0,40.0,78.0,43.0,6.0,77.0,77.0,6.0,42.0,43.0,7.0,40.0,6.0,43.0,40.0,42.0,6.0,No,Not_Applicable,0.0,English_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Undergrad,Associates,0.0,0.0,LT1,14_26wks,Worked,Naturalized,No_Drive,Employed_at_work,ENT2,1,1,White,LT_Bachelors,EAT3
2,P,2018GQ0000060,2,1.0,2001,1,36,1013097,88.0,18.0,2,NaN,1.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,1.0,2.0,NaN,NaN,NaN,2,2,2,1,2,2,2,0.0,NaN,NaN,NaN,1.0,5,NaN,NaN,NaN,NaN,NaN,3.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,5.0,2.0,2.0,2.0,0.0,0.0,17,0.0,2.0,15.0,16.0,0.0,2,0.0,0.0,0.0,NaN,2.0,NaN,2.0,2001.0,1,275,999,7.0,2,NaN,NaN,6.0,NaN,NaN,1,2,8680.0,NaN,NaN,1200.0,3700.0,36.0,6.0,722Z,1,NaN,NaN,4720.0,NaN,0.0,0.0,72,NaN,NaN,NaN,2,1,3,8,67,15,0,0,0,0,1,0,1,0,NaN,NaN,NaN,NaN,NaN,412010,NaN,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0.0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,88.0,89.0,15.0,13.0,86.0,90.0,86.0,14.0,161.0,12.0,88.0,163.0,159.0,165.0,88.0,15.0,160.0,87.0,88.0,89.0,88.0,87.0,15.0,13.0,88.0,88.0,88.0,13.0,163.0,12.0,86.0,163.0,161.0,159.0,88.0,13.0,161.0,92.0,84.0,91.0,87.0,86.0,12.0,13.0,89.0,88.0,88.0,14.0,166.0,12.0,89.0,163.0,159.0,165.0,88.0,13.0,165.0,89.0,89.0,85.0,88.0,89.0,13.0,15.0,88.0,88.0,86.0,12.0,163.0,13.0,88.0,163.0,161.0,162.0,87.0,12.0,162.0,88.0,87.0,88.0,No,No,0.0,Other_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Undergrad,HS_Diploma,0.0,0.0,BT1_5,Not_Worked,Not_Worked,Immigr_00s,No_Drive,Not_Labor,ENT2,0,0,Some_Other,LT_Bachelors,SAL2
3,P,2018GQ0000081,2,1.0,2401,1,36,1013097,109.0,85.0,1,NaN,NaN,1.0,1,2,2.0,1.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,1,2,1,1,2,2,2,0.0,NaN,NaN,NaN,2.0,2,2.0,2.0,1.0,2.0,1950.0,1.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,3.0,3.0,3.0,0.0,0.0,16,0.0,1.0,NaN,16.0,0.0,2,0.0,13700.0,0.0,NaN,3.0,NaN,NaN,NaN,4,999,999,NaN,1,NaN,NaN,6.0,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,3.0,None,1,NaN,NaN,NaN,NaN,0.0,13700.0,36,NaN,NaN,NaN,1,1,3,1,1,1,0,0,0,0,1,0,0,1,NaN,NaN,NaN,NaN,NaN,None,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0,0.0,0,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,107.0,17.0,196.0,112.0,112.0,111.0,210.0,108.0,18.0,108.0,200.0,195.0,106.0,109.0,200.0,17.0,106.0,15.0,18.0,105.0,108.0,17.0,203.0,107.0,105.0,109.0,202.0,111.0,18.0,107.0,205.0,196.0,102.0,108.0,202.0,17.0,107.0,17.0,17.0,112.0,110.0,197.0,15.0,104.0,108.0,107.0,17.0,111.0,203.0,107.0,18.0,15.0,109.0,109.0,15.0,196.0,109.0,191.0,205.0,107.0,108.0,191.0,16.0,111.0,109.0,110.0,15.0,109.0,199.0,110.0,17.0,15.0,111.0,107.0,17.0,196.0,109.0,200.0,198.0,111.0,No,Not_Applicable,0.0,English_Lang,2.0,Never_Served,LT_17yrold,0.0,0.0,Not_Attending,HS_Diploma,0.0,0.0,GT5,Not_Worked,Not_Reported,Naturalized,No_Drive,Not_Labor,No_Work,1,0,White,LT_Bachelors,No_Work
4,P,2018GQ0000103,2,1.0,1400,1,36,1013097,83.0,19.0,1,NaN,1.0,2.0,2,2,2.0,2.0,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,2,1,2,2,2,2,2,0.0,5.0,5.0,1.0,2.0,5,NaN,NaN,NaN,NaN,NaN,1.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5.0,3.0,3.0,3.0,0.0,0.0,17,0.0,3.0,15.0,19.0,0.0,2,0.0,0.0,870.0,4.0,1.0,5.0,1.0,NaN,2,50,425,NaN,2,5.0,NaN,1.0,NaN,NaN,1,1,8590.0,181.0,110.0,NaN,NaN,NaN,6.0,713Z,1,NaN,NaN,2723.0,NaN,870.0,870.0,36,NaN,1400.0,36.0,1,2,4,1,1,1,0,0,0,0,1,0,0,1,NaN,NaN,NaN,NaN,NaN,272023,NaN,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,NaN,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,82.0,12.0,151.0,83.0,12.0,10.0,83.0,85.0,82.0,84.0,83.0,152.0,81.0,13.0,154.0,82.0,149.0,83.0,13.0,153.0,83.0,12.0,149.0,83.0,13.0,13.0,83.0,84.0,82.0,81.0,81.0,152.0,83.0,11.0,154.0,83.0,151.0,85.0,13.0,13.0,81.0,151.0,13.0,81.0,153.0,154.0,81.0,80.0,86.0,80.0,82.0,13.0,80.0,155.0,12.0,83.0,10.0,84.0,153.0,10.0,83.0,154.0,10.0,84.0,153.0,153.0,81.0,82.0,83.0,82.0,81.0,12.0,80.0,154.0,12.0,80.0,12.0,83.0,152.0,154.0,No,No,0.0,English_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Undergrad,NoDegree_College,0.0,0.0,LT1,14_26wks,Worked,Naturalized,5_6_driver,Employed_at_work,ENT1,1,1,White,LT_Bachelors,ENT2

In [14]:
df_al.shape

(196967, 311)

In [15]:
df_paul.shape

(196967, 288)

In [16]:
def add_minutes(df_):
    """
    converting arrival at work and departure at work to minutes
    """
    
    dataframe = df_.copy()
    
    conditions = [
        dataframe['JWAP'].isin([1, 2, 3, 4, 5, 6, 7]),
        dataframe['JWAP'].isin([8, 9, 10]),
        dataframe['JWAP'].gt(10) & dataframe['JWAP'].lt(22),
        dataframe['JWAP'].gt(21)
    ]
    choices = [
        (dataframe['JWAP'] - 1) * 5,
        ((dataframe['JWAP'] - 8) * 5) + 40,
        ((dataframe['JWAP'] - 11) * 5) + 60,
        ((dataframe['JWAP'] - 22) * 5) + 120
    ]
    
    dataframe['JWAP_mins'] = np.select(conditions, choices, 0)
    
    conditions = [
        dataframe['JWDP'].isin([1, 2, 3, 4, 5, 6]),
        dataframe['JWDP'].gt(6) & dataframe['JWDP'].lt(20),
        dataframe['JWDP'].gt(19) & dataframe['JWDP'].lt(79),
        dataframe['JWDP'].gt(78) & dataframe['JWDP'].lt(133),
        dataframe['JWDP'].gt(132) & dataframe['JWDP'].lt(137),
        dataframe['JWDP'].gt(136) & dataframe['JWDP'].lt(149),
        dataframe['JWDP'].isin([149, 150])
    ]
    choices = [
        (dataframe['JWDP'] - 1) * 30,
        ((dataframe['JWDP'] - 7) * 10) + 180,
        ((dataframe['JWDP'] - 20) * 5) + 300,
        ((dataframe['JWDP'] - 79) * 10) + 600,
        ((dataframe['JWDP'] - 133) * 30) + 1140,
        ((dataframe['JWDP'] - 137) * 10) + 1260,
        ((dataframe['JWDP'] - 149) * 30) + 1380
    ]
    dataframe['JWDP_mins'] = np.select(conditions, choices, 0)
    
    conditions = [
        dataframe['JWAP_mins'] < dataframe['JWDP_mins'],
        dataframe['JWAP_mins'] > dataframe['JWDP_mins']
    ]
    choices = [
        (1440 - dataframe['JWDP_mins']) + dataframe['JWAP_mins'],
        dataframe['JWAP_mins'] - dataframe['JWDP_mins']
    ]
    dataframe['TOTAL_commute'] = np.select(conditions, choices, 0)
    
    return dataframe

In [17]:
df_al = add_minutes(df_al)

In [18]:
def dropping_features(df_):
    """
    Dropping features based off of 3 conditions.
    1. Dropping unwanted features
    2. Dropping duplicate columns after missing handled
    3. Dropping flags and weights
    """
    
    dataframe = df_.copy()
    # 1. Dropping Unwanted features
    dataframe.drop(columns = ['DIVISION','REGION','ST','DRAT','DRATX','GCM',
                              'HINS3','HINS5','HINS6','FOD1P','FOD2P','LANP','MIGPUMA',
                             'PAOC','PRIVCOV','PUBCOV','RAC2P','RAC3P','SFN','SFR'], inplace=True)
    
    # 2. Dropping duplicate columns after missing handled
    dataframe.drop(columns = ['DOUT', 'FER', 'INTP', 'LANX', 'MARHW', 'OIP',
                             'RETP', 'SCHG', 'SCHL', 'SEMP', 'SSIP', 'WKL', 'WKW',
                             'WRK', 'YOEP', 'DRIVESP', 'ESR', 'NAICSP', 'POBP','POWSP',
                             'RAC1P','SCIENGRLP', 'SOCP','NWAB', 'NWAV', 'NWLA'], inplace=True)
    
    # 3. Drpoping flags and weights
    dataframe.drop(columns =['FCITP', 'FDEYEP', 'FDOUTP',
                           'FDPHYP', 'FDREMP', 'FENGP', 'FFERP', 'FFODP', 'FGCLP', 'FHINS1P',
                           'FHINS3C', 'FHINS3P', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FINTP',
                           'FJWDP', 'FJWRIP', 'FJWTRP', 'FLANXP', 'FMARHDP', 'FMARHMP','JWAP',
                           'FMARHWP', 'FMARHYP', 'FMIGP', 'FMILPP','MIL', 'FOCCP', 'FPAP', 'FPERNP',
                           'FPINCP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSEMP', 'FWAGP', 'FWKLP',
                           'FWKWP', 'FWRKP', 'PWGTP1', 'PWGTP2', 'PWGTP6', 'PWGTP7',
                           'PWGTP11', 'PWGTP12', 'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16',
                           'PWGTP18', 'PWGTP19', 'PWGTP22', 'PWGTP27', 'PWGTP28', 'PWGTP29',
                           'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP41', 'PWGTP44', 'PWGTP45',
                           'PWGTP46', 'PWGTP49', 'PWGTP50', 'PWGTP53', 'PWGTP59', 'PWGTP60',
                           'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP67', 'PWGTP69', 'PWGTP70',
                           'PWGTP72', 'PWGTP73', 'PWGTP76', 'PWGTP78', 'PWGTP79','CITWP',
       'COW', 'DDRS', 'DEAR', 'DPHY', 'DREM', 'ENG', 'GCL', 'HINS1',
       'HINS2',  'HINS7', 'JWMNP', 'JWRIP', 'JWTR', 'MARHD',
       'MARHM', 'MARHT', 'MARHYP', 'MIG', 'MLPB', 'MLPCD', 'MLPE',
       'MLPFG', 'MLPH', 'MLPI', 'MLPJ', 'MLPK', 'NWLK', 'NWRE', 'PAP',
       'RELP', 'SCH', 'SSP', 'WAGP', 'WKHP', 'DECADE', 'DIS', 'ESP',
       'HICOV', 'HISP', 'INDP', 'JWDP', 'MIGSP', 'MSP', 'NOP', 'OC',
       'OCCP', 'PERNP', 'PINCP', 'POVPIP', 'POWPUMA', 'QTRBIR', 'RACWHT',
       'RC', 'SCIENGP', 'VPS', 'WAOB','FHINS4C','GCR'], inplace=True)
    
    return dataframe

In [19]:
df_al = dropping_features(df_al)

In [20]:
df_al.isna().sum()

RT               0
SERIALNO         0
SPORDER          0
PUMA             0
ADJINC           0
PWGTP            0
AGEP             0
CIT              0
DEYE             0
HINS4            0
MAR              0
MLPA             0
SEX              0
ANC              0
ANC1P            0
ANC2P            0
NATIVITY         0
RACAIAN          0
RACASN           0
RACBLK           0
RACNH            0
RACNUM           0
RACPI            0
RACSOR           0
FAGEP            0
FANCP            0
FCITWP           0
FCOWP            0
FDDRSP           0
FDEARP           0
FDISP            0
FDRATP           0
FDRATXP          0
FESRP            0
FGCMP            0
FGCRP            0
FHICOVP          0
FHINS2P          0
FHINS6P          0
FHINS7P          0
FHISP            0
FINDP            0
FJWMNP           0
FLANP            0
FMARP            0
FMARHTP          0
FMIGSP           0
FMILSP           0
FOIP             0
FPOBP            0
FPOWSP           0
FPRIVCOVP        0
FPUBCOVP         0
FRACP            0
FRELP            0
FSCHP            0
FSEXP            0
FSSIP            0
FSSP             0
FWKHP            0
FYOEP            0
PWGTP3           0
PWGTP4           0
PWGTP5           0
PWGTP8           0
PWGTP9           0
PWGTP10          0
PWGTP17          0
PWGTP20          0
PWGTP21          0
PWGTP23          0
PWGTP24          0
PWGTP25          0
PWGTP26          0
PWGTP30          0
PWGTP31          0
PWGTP32          0
PWGTP36          0
PWGTP37          0
PWGTP38          0
PWGTP39          0
PWGTP40          0
PWGTP42          0
PWGTP43          0
PWGTP47          0
PWGTP48          0
PWGTP51          0
PWGTP52          0
PWGTP54          0
PWGTP55          0
PWGTP56          0
PWGTP57          0
PWGTP58          0
PWGTP61          0
PWGTP65          0
PWGTP66          0
PWGTP68          0
PWGTP71          0
PWGTP74          0
PWGTP75          0
PWGTP77          0
PWGTP80          0
DOUT_cat         0
FER_cat          0
INTP_cat         0
LANX_cat         0
MARHW_cat        0
MIL_cat          0
MLPA_cat         0
OIP_cat          0
RETP_cat         0
SCHG_cat         0
SCHL_cat         0
SEMP_cat         0
SSIP_cat         0
WKL_cat          0
WKW_cat          0
WRK_cat          0
YOEP_cat         0
DRIVESP_cat      0
ESR_cat          0
NAICSP_cat       0
POBP_cat         0
POWSP_cat        0
RAC1P_cat        0
SCIENGRLP_cat    0
SOCP_cat         0
JWAP_mins        0
JWDP_mins        0
TOTAL_commute    0
dtype: int64

In [21]:
df_paul.columns.values

array(['RT', 'SERIALNO', 'DIVISION', 'SPORDER', 'PUMA', 'REGION', 'ST',
       'ADJINC', 'PWGTP', 'AGEP', 'CIT', 'CITWP', 'COW', 'DDRS', 'DEAR',
       'DEYE', 'DOUT', 'DPHY', 'DRAT', 'DRATX', 'DREM', 'ENG', 'FER',
       'GCL', 'GCM', 'GCR', 'HINS1', 'HINS2', 'HINS3', 'HINS4', 'HINS5',
       'HINS6', 'HINS7', 'INTP', 'JWMNP', 'JWRIP', 'JWTR', 'LANX', 'MAR',
       'MARHD', 'MARHM', 'MARHT', 'MARHW', 'MARHYP', 'MIG', 'MIL', 'MLPA',
       'MLPB', 'MLPCD', 'MLPE', 'MLPFG', 'MLPH', 'MLPI', 'MLPJ', 'MLPK',
       'NWAB', 'NWAV', 'NWLA', 'NWLK', 'NWRE', 'OIP', 'PAP', 'RELP',
       'RETP', 'SCH', 'SCHG', 'SCHL', 'SEMP', 'SEX', 'SSIP', 'SSP',
       'WAGP', 'WKHP', 'WKL', 'WKW', 'WRK', 'YOEP', 'ANC', 'ANC1P',
       'ANC2P', 'DECADE', 'DIS', 'DRIVESP', 'ESP', 'ESR', 'FOD1P',
       'FOD2P', 'HICOV', 'HISP', 'INDP', 'JWAP', 'JWDP', 'LANP',
       'MIGPUMA', 'MIGSP', 'MSP', 'NAICSP', 'NATIVITY', 'NOP', 'OC',
       'OCCP', 'PAOC', 'PERNP', 'PINCP', 'POBP', 'POVPIP', 'POWPUMA',
       'POWSP', 'PRIVCOV', 'PUBCOV', 'QTRBIR', 'RAC1P', 'RAC2P', 'RAC3P',
       'RACAIAN', 'RACASN', 'RACBLK', 'RACNH', 'RACNUM', 'RACPI',
       'RACSOR', 'RACWHT', 'RC', 'SCIENGP', 'SCIENGRLP', 'SFN', 'SFR',
       'SOCP', 'VPS', 'WAOB', 'FAGEP', 'FANCP', 'FCITP', 'FCITWP',
       'FCOWP', 'FDDRSP', 'FDEARP', 'FDEYEP', 'FDISP', 'FDOUTP', 'FDPHYP',
       'FDRATP', 'FDRATXP', 'FDREMP', 'FENGP', 'FESRP', 'FFERP', 'FFODP',
       'FGCLP', 'FGCMP', 'FGCRP', 'FHICOVP', 'FHINS1P', 'FHINS2P',
       'FHINS3C', 'FHINS3P', 'FHINS4C', 'FHINS4P', 'FHINS5C', 'FHINS5P',
       'FHINS6P', 'FHINS7P', 'FHISP', 'FINDP', 'FINTP', 'FJWDP', 'FJWMNP',
       'FJWRIP', 'FJWTRP', 'FLANP', 'FLANXP', 'FMARP', 'FMARHDP',
       'FMARHMP', 'FMARHTP', 'FMARHWP', 'FMARHYP', 'FMIGP', 'FMIGSP',
       'FMILPP', 'FMILSP', 'FOCCP', 'FOIP', 'FPAP', 'FPERNP', 'FPINCP',
       'FPOBP', 'FPOWSP', 'FPRIVCOVP', 'FPUBCOVP', 'FRACP', 'FRELP',
       'FRETP', 'FSCHGP', 'FSCHLP', 'FSCHP', 'FSEMP', 'FSEXP', 'FSSIP',
       'FSSP', 'FWAGP', 'FWKHP', 'FWKLP', 'FWKWP', 'FWRKP', 'FYOEP',
       'PWGTP1', 'PWGTP2', 'PWGTP3', 'PWGTP4', 'PWGTP5', 'PWGTP6',
       'PWGTP7', 'PWGTP8', 'PWGTP9', 'PWGTP10', 'PWGTP11', 'PWGTP12',
       'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16', 'PWGTP17', 'PWGTP18',
       'PWGTP19', 'PWGTP20', 'PWGTP21', 'PWGTP22', 'PWGTP23', 'PWGTP24',
       'PWGTP25', 'PWGTP26', 'PWGTP27', 'PWGTP28', 'PWGTP29', 'PWGTP30',
       'PWGTP31', 'PWGTP32', 'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP36',
       'PWGTP37', 'PWGTP38', 'PWGTP39', 'PWGTP40', 'PWGTP41', 'PWGTP42',
       'PWGTP43', 'PWGTP44', 'PWGTP45', 'PWGTP46', 'PWGTP47', 'PWGTP48',
       'PWGTP49', 'PWGTP50', 'PWGTP51', 'PWGTP52', 'PWGTP53', 'PWGTP54',
       'PWGTP55', 'PWGTP56', 'PWGTP57', 'PWGTP58', 'PWGTP59', 'PWGTP60',
       'PWGTP61', 'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP65', 'PWGTP66',
       'PWGTP67', 'PWGTP68', 'PWGTP69', 'PWGTP70', 'PWGTP71', 'PWGTP72',
       'PWGTP73', 'PWGTP74', 'PWGTP75', 'PWGTP76', 'PWGTP77', 'PWGTP78',
       'PWGTP79', 'PWGTP80', 'CIT_STATUS', 'BORN_CIT'], dtype=object)

In [22]:
df_paul = df_paul[['RT', 'SPORDER', 'PUMA', 'ADJINC', 'PWGTP', 'CITWP',
       'COW', 'DDRS', 'DEAR', 'DPHY', 'DREM', 'ENG', 'JWMNP', 'JWRIP', 'JWTR', 'MARHD',
       'MARHM', 'MARHT', 'MARHYP', 'MIG', 'MIL','MLPCD', 'MLPE',
       'MLPFG', 'MLPH', 'MLPI', 'MLPJ', 'MLPK', 'NWLK','PAP',
       'RELP', 'SCH', 'SSP', 'WAGP', 'WKHP', 'DECADE', 'DIS', 'ESP',
        'HISP', 'INDP', 'MIGSP', 'MSP', 'NOP', 'OC',
       'OCCP', 'PERNP', 'PINCP', 'QTRBIR', 'RACWHT',
       'RC', 'SCIENGP', 'VPS', 'WAOB','CIT_STATUS', 'BORN_CIT', 'HICOV']]

In [23]:
df_paul.isna().sum()

RT            0
SPORDER       0
PUMA          0
ADJINC        0
PWGTP         0
CITWP         0
COW           0
DDRS          0
DEAR          0
DPHY          0
DREM          0
ENG           0
JWMNP         0
JWRIP         0
JWTR          0
MARHD         0
MARHM         0
MARHT         0
MARHYP        0
MIG           0
MIL           0
MLPCD         0
MLPE          0
MLPFG         0
MLPH          0
MLPI          0
MLPJ          0
MLPK          0
NWLK          0
PAP           0
RELP          0
SCH           0
SSP           0
WAGP          0
WKHP          0
DECADE        0
DIS           0
ESP           0
HISP          0
INDP          0
MIGSP         0
MSP           0
NOP           0
OC            0
OCCP          0
PERNP         0
PINCP         0
QTRBIR        0
RACWHT        0
RC            0
SCIENGP       0
VPS           0
WAOB          0
CIT_STATUS    0
BORN_CIT      0
HICOV         0
dtype: int64

In [24]:
df_paul.head()

,RT,SPORDER,PUMA,ADJINC,PWGTP,CITWP,COW,DDRS,DEAR,DPHY,DREM,ENG,JWMNP,JWRIP,JWTR,MARHD,MARHM,MARHT,MARHYP,MIG,MIL,MLPCD,MLPE,MLPFG,MLPH,MLPI,MLPJ,MLPK,NWLK,PAP,RELP,SCH,SSP,WAGP,WKHP,DECADE,DIS,ESP,HISP,INDP,MIGSP,MSP,NOP,OC,OCCP,PERNP,PINCP,QTRBIR,RACWHT,RC,SCIENGP,VPS,WAOB,CIT_STATUS,BORN_CIT,HICOV
0,P,1.0,3802,1013097,145.0,1.0,2.0,2.0,2,2.0,2.0,1.0,201.0,0.0,14.0,3.0,3.0,3.0,1.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,3.0,0.0,5200.0,50.0,8.0,2,0.0,1,EDU,36,6.0,0.0,0.0,5110.0,5200.0,5200.0,4,1,3.0,1.0,16.0,5,0,0,1
1,P,1.0,2702,1013097,43.0,0.0,1.0,2.0,2,2.0,2.0,5.0,2.0,0.0,10.0,3.0,3.0,3.0,1.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,2.0,0.0,1000.0,2.0,0.0,2,0.0,1,ENT2,36,6.0,0.0,0.0,4110.0,1000.0,1000.0,2,1,3.0,0.0,16.0,1,1,1,1
2,P,1.0,2001,1013097,88.0,0.0,1.0,2.0,2,2.0,2.0,1.0,201.0,0.0,14.0,3.0,3.0,3.0,1.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,2.0,0.0,0.0,0.0,0.0,2,0.0,2,ENT2,36,6.0,0.0,0.0,4720.0,0.0,0.0,3,0,3.0,0.0,16.0,2,1,1,1
3,P,1.0,2401,1013097,109.0,0.0,10.0,1.0,1,1.0,1.0,5.0,201.0,0.0,14.0,2.0,2.0,2.0,1950.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,16,1.0,13700.0,0.0,0.0,0.0,1,0.0,1,None,36,3.0,0.0,0.0,1.0,0.0,13700.0,3,1,3.0,0.0,16.0,1,1,1,1
4,P,1.0,1400,1013097,83.0,0.0,1.0,2.0,2,2.0,2.0,5.0,5.0,5.0,1.0,3.0,3.0,3.0,1.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,3.0,0.0,870.0,4.0,0.0,2,0.0,1,ENT1,36,6.0,0.0,0.0,2723.0,870.0,870.0,4,1,3.0,0.0,16.0,1,1,1,1

In [25]:
nys = pd.merge(df_al, df_paul, left_index=True, right_index=True)

In [26]:
nys.drop(columns = [ 'FAGEP', 'FANCP', 'FCITWP','HINS4',
       'FCOWP', 'FDDRSP', 'FDEARP', 'FDISP', 'FDRATP', 'FDRATXP', 'FESRP',
       'FGCMP', 'FGCRP', 'FHICOVP', 'FHINS2P', 'FHINS6P', 'FHINS7P',
       'FHISP', 'FINDP', 'FJWMNP', 'FLANP', 'FMARP', 'FMARHTP', 'FMIGSP',
       'FMILSP', 'FOIP', 'FPOBP', 'FPOWSP', 'FPRIVCOVP', 'FPUBCOVP',
       'FRACP', 'FRELP', 'FSCHP', 'FSEXP', 'FSSIP', 'FSSP', 'FWKHP',
       'FYOEP', 'PWGTP3', 'PWGTP4', 'PWGTP5', 'PWGTP8', 'PWGTP9',
       'PWGTP10', 'PWGTP17', 'PWGTP20', 'PWGTP21', 'PWGTP23', 'PWGTP24',
       'PWGTP25', 'PWGTP26', 'PWGTP30', 'PWGTP31', 'PWGTP32', 'PWGTP36',
       'PWGTP37', 'PWGTP38', 'PWGTP39', 'PWGTP40', 'PWGTP42', 'PWGTP43',
       'PWGTP47', 'PWGTP48', 'PWGTP51', 'PWGTP52', 'PWGTP54', 'PWGTP55',
       'PWGTP56', 'PWGTP57', 'PWGTP58', 'PWGTP61', 'PWGTP65', 'PWGTP66',
       'PWGTP68', 'PWGTP71', 'PWGTP74', 'PWGTP75', 'PWGTP77', 'PWGTP80','RT_x', 'SPORDER_x', 'PUMA_x', 'ADJINC_x', 'PWGTP_x'], inplace=True)

In [27]:
nys.columns.values

array(['SERIALNO', 'AGEP', 'CIT', 'DEYE', 'MAR', 'MLPA', 'SEX', 'ANC',
       'ANC1P', 'ANC2P', 'NATIVITY', 'RACAIAN', 'RACASN', 'RACBLK',
       'RACNH', 'RACNUM', 'RACPI', 'RACSOR', 'DOUT_cat', 'FER_cat',
       'INTP_cat', 'LANX_cat', 'MARHW_cat', 'MIL_cat', 'MLPA_cat',
       'OIP_cat', 'RETP_cat', 'SCHG_cat', 'SCHL_cat', 'SEMP_cat',
       'SSIP_cat', 'WKL_cat', 'WKW_cat', 'WRK_cat', 'YOEP_cat',
       'DRIVESP_cat', 'ESR_cat', 'NAICSP_cat', 'POBP_cat', 'POWSP_cat',
       'RAC1P_cat', 'SCIENGRLP_cat', 'SOCP_cat', 'JWAP_mins', 'JWDP_mins',
       'TOTAL_commute', 'RT_y', 'SPORDER_y', 'PUMA_y', 'ADJINC_y',
       'PWGTP_y', 'CITWP', 'COW', 'DDRS', 'DEAR', 'DPHY', 'DREM', 'ENG',
       'JWMNP', 'JWRIP', 'JWTR', 'MARHD', 'MARHM', 'MARHT', 'MARHYP',
       'MIG', 'MIL', 'MLPCD', 'MLPE', 'MLPFG', 'MLPH', 'MLPI', 'MLPJ',
       'MLPK', 'NWLK', 'PAP', 'RELP', 'SCH', 'SSP', 'WAGP', 'WKHP',
       'DECADE', 'DIS', 'ESP', 'HISP', 'INDP', 'MIGSP', 'MSP', 'NOP',
       'OC', 'OCCP', 'PERNP', 'PINCP', 'QTRBIR', 'RACWHT', 'RC',
       'SCIENGP', 'VPS', 'WAOB', 'CIT_STATUS', 'BORN_CIT', 'HICOV'],
      dtype=object)

In [28]:
nys.head()

,SERIALNO,AGEP,CIT,DEYE,MAR,MLPA,SEX,ANC,ANC1P,ANC2P,NATIVITY,RACAIAN,RACASN,RACBLK,RACNH,RACNUM,RACPI,RACSOR,DOUT_cat,FER_cat,INTP_cat,LANX_cat,MARHW_cat,MIL_cat,MLPA_cat,OIP_cat,RETP_cat,SCHG_cat,SCHL_cat,SEMP_cat,SSIP_cat,WKL_cat,WKW_cat,WRK_cat,YOEP_cat,DRIVESP_cat,ESR_cat,NAICSP_cat,POBP_cat,POWSP_cat,RAC1P_cat,SCIENGRLP_cat,SOCP_cat,JWAP_mins,JWDP_mins,TOTAL_commute,RT_y,SPORDER_y,PUMA_y,ADJINC_y,PWGTP_y,CITWP,COW,DDRS,DEAR,DPHY,DREM,ENG,JWMNP,JWRIP,JWTR,MARHD,MARHM,MARHT,MARHYP,MIG,MIL,MLPCD,MLPE,MLPFG,MLPH,MLPI,MLPJ,MLPK,NWLK,PAP,RELP,SCH,SSP,WAGP,WKHP,DECADE,DIS,ESP,HISP,INDP,MIGSP,MSP,NOP,OC,OCCP,PERNP,PINCP,QTRBIR,RACWHT,RC,SCIENGP,VPS,WAOB,CIT_STATUS,BORN_CIT,HICOV
0,2018GQ0000012,26.0,5,2,5,3.0,2,1,26,999,2,0,0,0,0,1,0,0,No,No,0.0,Other_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Graduate,Bachelors,0.0,0.0,LT1,LT_14wks,Not_Reported,Immigr_10s,No_Drive,Not_Labor,EDU,0,0,White,No,OFF3,0.0,0.0,0.0,P,1.0,3802,1013097,145.0,1.0,2.0,2.0,2,2.0,2.0,1.0,201.0,0.0,14.0,3.0,3.0,3.0,1.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,3.0,0.0,5200.0,50.0,8.0,2,0.0,1,EDU,36,6.0,0.0,0.0,5110.0,5200.0,5200.0,4,1,3.0,1.0,16.0,5,0,0,1
1,2018GQ0000040,21.0,1,2,5,3.0,1,1,51,999,1,0,0,0,0,1,0,0,No,Not_Applicable,0.0,English_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Undergrad,Associates,0.0,0.0,LT1,14_26wks,Worked,Naturalized,No_Drive,Employed_at_work,ENT2,1,1,White,LT_Bachelors,EAT3,1425.0,1410.0,15.0,P,1.0,2702,1013097,43.0,0.0,1.0,2.0,2,2.0,2.0,5.0,2.0,0.0,10.0,3.0,3.0,3.0,1.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,2.0,0.0,1000.0,2.0,0.0,2,0.0,1,ENT2,36,6.0,0.0,0.0,4110.0,1000.0,1000.0,2,1,3.0,0.0,16.0,1,1,1,1
2,2018GQ0000060,18.0,2,2,5,3.0,2,1,275,999,1,0,0,0,0,1,0,1,No,No,0.0,Other_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Undergrad,HS_Diploma,0.0,0.0,BT1_5,Not_Worked,Not_Worked,Immigr_00s,No_Drive,Not_Labor,ENT2,0,0,Some_Other,LT_Bachelors,SAL2,0.0,0.0,0.0,P,1.0,2001,1013097,88.0,0.0,1.0,2.0,2,2.0,2.0,1.0,201.0,0.0,14.0,3.0,3.0,3.0,1.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,2.0,0.0,0.0,0.0,0.0,2,0.0,2,ENT2,36,6.0,0.0,0.0,4720.0,0.0,0.0,3,0,3.0,0.0,16.0,2,1,1,1
3,2018GQ0000081,85.0,1,2,2,3.0,2,4,999,999,1,0,0,0,0,1,0,0,No,Not_Applicable,0.0,English_Lang,2.0,Never_Served,LT_17yrold,0.0,0.0,Not_Attending,HS_Diploma,0.0,0.0,GT5,Not_Worked,Not_Reported,Naturalized,No_Drive,Not_Labor,No_Work,1,0,White,LT_Bachelors,No_Work,0.0,0.0,0.0,P,1.0,2401,1013097,109.0,0.0,10.0,1.0,1,1.0,1.0,5.0,201.0,0.0,14.0,2.0,2.0,2.0,1950.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,16,1.0,13700.0,0.0,0.0,0.0,1,0.0,1,None,36,3.0,0.0,0.0,1.0,0.0,13700.0,3,1,3.0,0.0,16.0,1,1,1,1
4,2018GQ0000103,19.0,1,2,5,3.0,2,2,50,425,1,0,0,0,0,1,0,0,No,No,0.0,English_Lang,Unknown,Never_Served,LT_17yrold,0.0,0.0,Undergrad,NoDegree_College,0.0,0.0,LT1,14_26wks,Worked,Naturalized,5_6_driver,Employed_at_work,ENT1,1,1,White,LT_Bachelors,ENT2,915.0,910.0,5.0,P,1.0,1400,1013097,83.0,0.0,1.0,2.0,2,2.0,2.0,5.0,5.0,5.0,1.0,3.0,3.0,3.0,1.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,0.0,17,3.0,0.0,870.0,4.0,0.0,2,0.0,1,ENT1,36,6.0,0.0,0.0,2723.0,870.0,870.0,4,1,3.0,0.0,16.0,1,1,1,1

In [30]:
nys.shape

(196967, 102)

In [29]:
nys.isna().sum()

SERIALNO         0
AGEP             0
CIT              0
DEYE             0
MAR              0
MLPA             0
SEX              0
ANC              0
ANC1P            0
ANC2P            0
NATIVITY         0
RACAIAN          0
RACASN           0
RACBLK           0
RACNH            0
RACNUM           0
RACPI            0
RACSOR           0
DOUT_cat         0
FER_cat          0
INTP_cat         0
LANX_cat         0
MARHW_cat        0
MIL_cat          0
MLPA_cat         0
OIP_cat          0
RETP_cat         0
SCHG_cat         0
SCHL_cat         0
SEMP_cat         0
SSIP_cat         0
WKL_cat          0
WKW_cat          0
WRK_cat          0
YOEP_cat         0
DRIVESP_cat      0
ESR_cat          0
NAICSP_cat       0
POBP_cat         0
POWSP_cat        0
RAC1P_cat        0
SCIENGRLP_cat    0
SOCP_cat         0
JWAP_mins        0
JWDP_mins        0
TOTAL_commute    0
RT_y             0
SPORDER_y        0
PUMA_y           0
ADJINC_y         0
PWGTP_y          0
CITWP            0
COW              0
DDRS             0
DEAR             0
DPHY             0
DREM             0
ENG              0
JWMNP            0
JWRIP            0
JWTR             0
MARHD            0
MARHM            0
MARHT            0
MARHYP           0
MIG              0
MIL              0
MLPCD            0
MLPE             0
MLPFG            0
MLPH             0
MLPI             0
MLPJ             0
MLPK             0
NWLK             0
PAP              0
RELP             0
SCH              0
SSP              0
WAGP             0
WKHP             0
DECADE           0
DIS              0
ESP              0
HISP             0
INDP             0
MIGSP            0
MSP              0
NOP              0
OC               0
OCCP             0
PERNP            0
PINCP            0
QTRBIR           0
RACWHT           0
RC               0
SCIENGP          0
VPS              0
WAOB             0
CIT_STATUS       0
BORN_CIT         0
HICOV            0
dtype: int64

In [31]:
nys.to_csv('nys_data.csv')

### You can stop here for the fully cleaned data

In [ ]:
df = pd.read_csv('csv_hny/psam_h36.csv')

In [ ]:
df.shape

In [ ]:
df.describe(include = 'all')

In [ ]:
synthetic = df.groupby(['SERIALNO']).agg({'PINCP':'sum'}).reset_index()
synthetic.columns = ['SERIALNO', 'synt_FINCP']
_df = pd.merge(nys, synthetic, on='SERIALNO')
_df