In [1]:
def alberts_turn(dataframe):
    """
    'DIVISION', 'REGION', 'ST', 'AGE', 'CITIZEN', 'DEYE', 'DIS_ALONE',
       'DIS_VETP', 'DIS_VET', 'FER', 'GCM', 'GCR', 'MEDCAID', 'TRICARE',
       'HI_VA', 'INTP', 'LANX', 'MAR', 'MARHW', 'MIL', 'MLPA', 'NWAB',
       'NWAV', 'NWLA', 'OIP', 'RETP', 'SCHG', 'SCHL', 'SEMP', 'SEX',
       'SSIP', 'WKL', 'WKW', 'WRK', 'YR_ENTER_US', 'ANC', 'ANCES1',
       'ANC2P', 'DRIVESP', 'ESR', 'DEGREE1', 'DEGREE2', 'WK_ARR_TME',
       'LAN_HOME', 'MIGPUMA', 'NAICSP', 'NATIVITY', 'PAOC', 'POBP',
       'POWSP', 'PRIVCOV', 'PUBCOV', 'RAC1P', 'RAC2P', 'RAC3P', 'RACAIAN',
       'RACASN', 'RACBLK', 'RACNH', 'RACNUM', 'RACPI', 'RACSOR',
       'SCIENGRLP', 'SFN', 'SFR', 'SOCP', 'FCITP', 'FDEYEP', 'FDOUTP',
       'FDPHYP', 'FDREMP', 'FENGP', 'FFERP', 'FFODP', 'FGCLP', 'FHINS1P',
       'FHINS3C', 'FHINS3P', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FINTP',
       'FJWDP', 'FJWRIP', 'FJWTRP', 'FLANXP', 'FMARHDP', 'FMARHMP',
       'FMARHWP', 'FMARHYP', 'FMIGP', 'FMILPP', 'FOCCP', 'FPAP', 'FPERNP',
       'FPINCP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSEMP', 'FWAGP', 'FWKLP',
       'FWKWP', 'FWRKP', 'PWGTP1', 'PWGTP2', 'PWGTP6', 'PWGTP7',
       'PWGTP11', 'PWGTP12', 'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16',
       'PWGTP18', 'PWGTP19', 'PWGTP22', 'PWGTP27', 'PWGTP28', 'PWGTP29',
       'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP41', 'PWGTP44', 'PWGTP45',
       'PWGTP46', 'PWGTP49', 'PWGTP50', 'PWGTP53', 'PWGTP59', 'PWGTP60',
       'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP67', 'PWGTP69', 'PWGTP70',
       'PWGTP72', 'PWGTP73', 'PWGTP76', 'PWGTP78', 'PWGTP79'
       
    """
    # DIVISION
    dataframe.drop(columns=['DIVISION'], inplace=True)
    
    # REGION
    dataframe.drop(columns=['REGION'], inplace=True)
    
    # ST
    dataframe.drop(columns=['ST'], inplace=True)
    
    # AGE
    # Keep AGE as is dataframe['AGEP']
    
    # CITIZEN
    # Keep CITIZEN as is dataframe['CIT']
    
    # DEYE
    # Keep DEYE as is dataframe['DEYE']
    
    # DIS_ALONE
    conditions = [dataframe['DOUT'].eq(1), dataframe['DOUT'].eq(2)]
    choices = ['Yes', 'No']
    
    dataframe['DOUT'] = np.select(conditions, choices, 'LT_15yrs')
    
    # DIS_VETP
    dataframe.drop(columns=['DRAT'], inplace=True)
    
    # DIS_VET
    dataframe.drop(columns=['DRATX'], inplace=True)
    
    # FER
    conditions = [dataframe['FER'].eq(1), dataframe['FER'].eq(2)]
    choices = ['Yes', 'No']
    
    dataframe['FER'] = np.select(conditions, choices, 'Not_Applicable')
    
    # GCM
    dataframe.drop(columns=['GCM'], inplace=True)
    
    # MEDCAID
    dataframe.drop(columns=['HINS3'], inplace=True)
    
    # TRICARE
    dataframe.drop(columns=['HINS5'], inplace=True)
    
    # HI_VA
    dataframe.drop(columns=['HINS6'], inplace=True)
    
    # INTP
    dataframe['INTP'] = np.where(dataframe['INTP'].isna(), 0, dataframe['INTP'])
    
    # LANX
    conditions = [dataframe['LANX'].eq(1), dataframe['LANX'].eq(2)]
    choices = ['Other_Lang', 'English_Lang']
    
    dataframe['LANX'] = np.select(conditions, choices, 'Baby_Lang')
    
    # MAR
    # Keep MAR as is dataframe['MAR']
    
    # MARHW
    dataframe['MARHW'] = np.where(dataframe['MARHW'].isna(), 'Unknown', dataframe['MARHW'])
    

    
    # MIL
    conditions = [dataframe['MIL'].eq(1), dataframe['MIL'].eq(2), dataframe['MIL'].eq(3), dataframe['MIL'].eq(4)]
    choices = ['Cur_Active', 'Past_Active', 'Cond_Active', 'Never_Served']
    
    dataframe['MIL'] = np.select(conditions, choices, 'LT_17yrold')
    
    # MLPA
    conditions = [dataframe['MLPA'].eq(0), dataframe['MLPA'].eq(1)]
    choices = ['No_Served', 'Yes_Served']
    
    dataframe['MLPA'] = np.select(conditions, choices, 'LT_17yrold')
    
    # OIP
    dataframe['OIP'] = np.where(dataframe['OIP'].isna(), 0, dataframe['OIP'])
    
    # RETP
    dataframe['RETP'] = np.where(dataframe['RETP'].isna(), 0 , dataframe['RETP'])
    
    # SCHG
    conditions = [
        dataframe['SCHG'].eq(1), dataframe['SCHG'].eq(2), dataframe['SCHG'].eq(3), dataframe['SCHG'].eq(4), 
        dataframe['SCHG'].eq(5), dataframe['SCHG'].eq(6), dataframe['SCHG'].eq(7), dataframe['SCHG'].eq(8), 
        dataframe['SCHG'].eq(9), dataframe['SCHG'].eq(10), dataframe['SCHG'].eq(11), dataframe['SCHG'].eq(12),
        dataframe['SCHG'].eq(13), dataframe['SCHG'].eq(14), dataframe['SCHG'].eq(15), dataframe['SCHG'].eq(16)
    ]
    choices = [
        'Nursery', 'Kindergarten', 'Grade_1', 'Grade_2',
        'Grade_3', 'Grade_4', 'Grade_5', 'Grade_6',
        'Grade_7', 'Grade_8', 'Grade_9', 'Grade_10',
        'Grade_11', 'Grade_12', 'Undergrad', 'Graduate'
    ]
    
    dataframe['SCHG'] = np.select(conditions,choices, 'Not_Attending')
    
    # SCHL
        conditions = [
        dataframe['SCHL'].eq(1), dataframe['SCHL'].eq(2), dataframe['SCHL'].eq(3), dataframe['SCHL'].eq(4), 
        dataframe['SCHL'].eq(5), dataframe['SCHL'].eq(6), dataframe['SCHL'].eq(7), dataframe['SCHL'].eq(8), 
        dataframe['SCHL'].eq(9), dataframe['SCHL'].eq(10), dataframe['SCHL'].eq(11), dataframe['SCHL'].eq(12),
        dataframe['SCHL'].eq(13), dataframe['SCHL'].eq(14), dataframe['SCHL'].eq(15), dataframe['SCHL'].eq(16)
    ]
    choices = [
        'No_School', 'Nursery', 'Kindergarten', 'Grade_1', 
        'Grade_2', 'Grade_3', 'Grade_4', 'Grade_5', 
        'Grade_6', 'Grade_7', 'Grade_8', 'Grade_9', 
        'Grade_10', 'Grade_11', 'Grade_12', 'HS_Diploma', 
        'GED_alt', 'LT1_College', 'NoDegree_College','Associates', 
        ' Bachelors', 'Masters', 'Professional', 'Doctorate'
        
    ]
    
    dataframe['SCHL'] = np.select(conditions,choices, 'LT_3yrold')
    
    # SEMP
    dataframe['SEMP'] = np.where(dataframe['SEMP'].isna(), 0, dataframe['SEMP'])
    
    # SEX
    # Keep SEX as is dataframe['SEX']
    
    # SSIP
    dataframe['SSIP'] = np.where(dataframe['SSIP'].isna(), 0 , dataframe['SSIP'])
    
    # WKL
    conditions = [dataframe['WKL'].eq(1), dataframe['WKL'].eq(2), dataframe['WKL'].eq(3)]
    choices = ['LT1', 'BT1_5', 'GT5']
    
    dataframe['WKL'] = np.select(conditions, choices, 'LT_16yrsold')
    
    # WKW
    conditions = [
        dataframe['WKW'].eq(1), dataframe['WKW'].eq(2), dataframe['WKW'].eq(3),
        dataframe['WKW'].eq(4), dataframe['WKW'].eq(5), dataframe['WKW'].eq(6)
    ]
    choices = [
        '50_52wks', '48_49wks', '40_47wks',
        '27_39wks', '14_26wks', 'LT_14wks'
    ]
    
    dataframe['WKW'] = np.select(conditions, choices, 'Not_Worked')
    
    # WRK
    conditions = [dataframe['WRK'].eq(1), dataframe['WRK'].eq(2)]
    choices = ['Worked', 'Not_Worked']
    
    dataframe['WRK'] = np.select(conditions, choices, 'Not_Reported')
    
    # YR_ENTER_US
    conditions = [
        dataframe['YOEP'].lt(1949.1), 
        dataframe['YOEP'].lt(1959.1) & dataframe['YEOP'].gt(1949.9),
        dataframe['YOEP'].lt(1969.1) & dataframe['YEOP'].gt(1959.9),
        dataframe['YOEP'].lt(1979.1) & dataframe['YEOP'].gt(1969.9),
        dataframe['YOEP'].lt(1989.1) & dataframe['YEOP'].gt(1979.9),
        dataframe['YOEP'].lt(1999.1) & dataframe['YEOP'].gt(1989.9),
        dataframe['YOEP'].lt(2009.1) & dataframe['YEOP'].gt(1999.9),
        dataframe['YOEP'].lt(2019.1) & dataframe['YEOP'].gt(2009.9),
        dataframe['YOEP'].isna()
    ]
    choices = [
        'Below_50s',
        'Immigr_50s',
        'Immigr_60s',
        'Immigr_70s',
        'Immigr_80s',
        'Immigr_90s',
        'Immigr_00s',
        'Immigr_10s',
        'Naturalized'
    ]
    
    dataframe['YOEP'] = np.selection(conditions,choices, 'Unknown')
    
    # ANC
    # Keep ANC as is dataframe['ANC']
    
    # ANCES1
    # Keep ANCES1 as is dataframe['ANC1P']
    
    # ANC2P
    # Keep ANC2P as is dataframe['ANC2P']
    
    
    # DRIVESP
    conditions = [dataframe['DRIVESP'].eq(1), dataframe['DRIVESP'].eq(2), dataframe['DRIVESP'].eq(3),
                 dataframe['DRIVESP'].eq(4), dataframe['DRIVESP'].eq(5), dataframe['DRIVESP'].eq(6)]
    choices = ['1_driver', '2_driver', '3_driver',
              '4_driver', '5_6_driver', 'GT7_driver']
    
    dataframe['DRIVESP'] = np.select(conditions, choices, 'No_Drive')
    

    
    # ESR
    conditions = [dataframe['ESR'].eq(1), dataframe['ESR'].eq(2), dataframe['ESR'].eq(3),
                 dataframe['ESR'].eq(4), dataframe['ESR'].eq(5), dataframe['ESR'].eq(6)]
    choices = ['Employed_at_work', 'Employed_not_work', 'Unemployed',
              'ArmedForces_at_work', 'ArmedForces_not_work', 'Not_Labor']
    
    dataframe['ESR'] = np.select(conditions, choices, 'LT_16yrsold')
    
    # DEGREE1
    dataframe.drop(columns=['FOD1P'], inplace=True)
    
    # DEGREE2
    dataframe.drop(columns=['FOD2P'], inplace=True)
    
    # WK_ARR_TME
    # Keep WK_ARR_TIME as is dataframe['JWAP']
    
    # LAN_HOME
    dataframe.drop(columns=['LANP'], inplace=True)
    
    # MIGPUMA
    dataframe.drop(columns['MIGPUMA'], inplace=True)
    
    # NAICSP
    dataframe['NAICSP'].fillna('None', inplace=True)
    conditions = [
        dataframe['NAICSP'].str.startswith('11'),
        dataframe['NAICSP'].str.startswith('21'),
        dataframe['NAICSP'].str.startswith('22'),
        dataframe['NAICSP'].str.startswith('23'),
        dataframe['NAICSP'].str.startswith('31'),
        dataframe['NAICSP'].str.startswith('32'),
        dataframe['NAICSP'].str.startswith('33'),
        dataframe['NAICSP'].str.startswith('3M'),
        dataframe['NAICSP'].str.startswith('42'),
        dataframe['NAICSP'].str.startswith('44'),
        dataframe['NAICSP'].str.startswith('45'),
        dataframe['NAICSP'].str.startswith('4M'),
        dataframe['NAICSP'].str.startswith('51'),
        dataframe['NAICSP'].str.startswith('52'),
        dataframe['NAICSP'].str.startswith('53'),
        dataframe['NAICSP'].str.startswith('54'),
        dataframe['NAICSP'].str.startswith('55'),
        dataframe['NAICSP'].str.startswith('56'),
        dataframe['NAICSP'].str.startswith('61'),
        dataframe['NAICSP'].str.startswith('62'),
        dataframe['NAICSP'].str.startswith('71'),
        dataframe['NAICSP'].str.startswith('72'),
        dataframe['NAICSP'].str.startswith('81'),
        dataframe['NAICSP'].str.startswith('92'),
        dataframe['NAICSP'].str.startswith('99'),
    ]
    choices = [
        'AGR',
        'EXT',
        'UTL',
        'CON',
        'MFG1',
        'MFG2',
        'MFG3',
        'MFG3',
        'WHL',
        'RET1',
        'RET2',
        'RET2',
        'INF',
        'FIN1',
        'FIN2',
        'PRF1',
        'PRF2',
        'PRF3',
        'EDU',
        'MED',
        'ENT1',
        'ENT2',
        'SRV',
        'ADM',
        'No_Work'
    ]
    
    dataframe['NAICSP'] = np.select(conditions, choices, 'No_Work')
    
    # NATIVITY
    # Keep NATIVITY as is dataframe['NATIVITY']
    
    # PAOC
    dataframe.drop(columns=['PAOC'], inplace=True)
    
    # 
     """ 'ESR', 'DEGREE1', 'DEGREE2', 'WK_ARR_TME',
       'LAN_HOME', 'MIGPUMA', 'NAICSP', 'NATIVITY', 'PAOC', 'POBP',
       'POWSP', 'PRIVCOV', 'PUBCOV', 'RAC1P', 'RAC2P', 'RAC3P', 'RACAIAN',
       'RACASN', 'RACBLK', 'RACNH', 'RACNUM', 'RACPI', 'RACSOR',
       'SCIENGRLP', 'SFN', 'SFR', 'SOCP', 'FCITP', 'FDEYEP', 'FDOUTP',
       'FDPHYP', 'FDREMP', 'FENGP', 'FFERP', 'FFODP', 'FGCLP', 'FHINS1P',
       'FHINS3C', 'FHINS3P', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FINTP',
       'FJWDP', 'FJWRIP', 'FJWTRP', 'FLANXP', 'FMARHDP', 'FMARHMP',
       'FMARHWP', 'FMARHYP', 'FMIGP', 'FMILPP', 'FOCCP', 'FPAP', 'FPERNP',
       'FPINCP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSEMP', 'FWAGP', 'FWKLP',
       'FWKWP', 'FWRKP', 'PWGTP1', 'PWGTP2', 'PWGTP6', 'PWGTP7',
       'PWGTP11', 'PWGTP12', 'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16',
       'PWGTP18', 'PWGTP19', 'PWGTP22', 'PWGTP27', 'PWGTP28', 'PWGTP29',
       'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP41', 'PWGTP44', 'PWGTP45',
       'PWGTP46', 'PWGTP49', 'PWGTP50', 'PWGTP53', 'PWGTP59', 'PWGTP60',
       'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP67', 'PWGTP69', 'PWGTP70',
       'PWGTP72', 'PWGTP73', 'PWGTP76', 'PWGTP78', 'PWGTP79'
       
    """
    # POBP
    dataframe['POBP'] = np.where(dataframe['POBP'].eq(36), 1, 0)
    
    
    # POWSP
    dataframe['POWSP'] = np.where(dataframe['POWSP'].eq(36), 1, 0)
    
    # PRIVCOV
    dataframe.drop(columns=['PRIVCOV'], inplace=True)
    
    # PUBCOV
    dataframe.drop(columns=['PUBCOV'], inplace=True)
    
    # RAC1P
    conditions = [
        dataframe['RAC1P'].eq(1), dataframe['RAC1P'].eq(2), dataframe['RAC1P'].eq(3),
        dataframe['RAC1P'].eq(4), dataframe['RAC1P'].eq(5), dataframe['RAC1P'].eq(6),
        dataframe['RAC1P'].eq(7), dataframe['RAC1P'].eq(8), dataframe['RAC1P'].eq(9),
    ]
    choices = [
        'White', 'Black', 'American_Indian',
        'Alaska_Native', 'American_Indian',' Asian',
        'Native_Hawaii', 'Some_Other', 'GT2_race'
    ]
    
    dataframe['RAC1P'] = np.select(conditions, choices, 'Unknown')
    
    # RAC2P
    dataframe.drop(columns=['RAC2P'], inplace=True)
    
    # RAC3P
    dataframe.drop(columns=['RAC3P'], inplace=True)
    
    # RACAIAN
    # Keep as is
    
    # RACASN
    # Keep as is
    
    # RACBLK
    # Keep as is
    
    # RACNH
    # Keep as is
    
    # RACNUM
    # Keep as is
    
    # RACPI
    # Keep as is
    
    # RACSOR
    # Keep as is
    
    # SCIENGRLP
    conditions = [dataframe['SCIENGRLP'].eq(1), dataframe['SCIENGRLP'].eq(2)]
    choices = ['Yes', 'No']
    
    dataframe['SCIENGRLP'] = np.select(conditions, choices, 'LT_Bachelors')
    
    # SFN
    dataframe.drop(columns = ['SFN'], inplace=True)
    
    # SFR
    dataframe.drop(columns=['SFR'], inplace=True)
    
    # SOCP
    
    dataframe['SOCP'].fillna('None', inplace=True)
    conditions = [
        dataframe['SOCP'].str.startswith('111'),
        dataframe['SOCP'].str.startswith('112'),
        dataframe['SOCP'].str.startswith('113'),
        dataframe['SOCP'].str.startswith('119'),
        dataframe['SOCP'].str.startswith('131'),
        dataframe['SOCP'].str.startswith('132'),
        dataframe['SOCP'].str.startswith('151'),
        dataframe['SOCP'].str.startswith('152'),
        dataframe['SOCP'].str.startswith('171'),
        dataframe['SOCP'].str.startswith('172'),
        dataframe['SOCP'].str.startswith('173'),
        dataframe['SOCP'].str.startswith('191'),
        dataframe['SOCP'].str.startswith('192'),
        dataframe['SOCP'].str.startswith('193'),
        dataframe['SOCP'].str.startswith('194'),
        dataframe['SOCP'].str.startswith('195'),
        dataframe['SOCP'].str.startswith('211'),
        dataframe['SOCP'].str.startswith('212'),
        dataframe['SOCP'].str.startswith('231'),
        dataframe['SOCP'].str.startswith('232'),#20
        dataframe['SOCP'].str.startswith('251'),
        dataframe['SOCP'].str.startswith('252'),
        dataframe['SOCP'].str.startswith('253'),
        dataframe['SOCP'].str.startswith('254'),
        dataframe['SOCP'].str.startswith('259'),
        dataframe['SOCP'].str.startswith('271'),
        dataframe['SOCP'].str.startswith('272'),
        dataframe['SOCP'].str.startswith('273'),
        dataframe['SOCP'].str.startswith('274'),
        dataframe['SOCP'].str.startswith('291'),
        dataframe['SOCP'].str.startswith('292'),
        dataframe['SOCP'].str.startswith('299'),
        dataframe['SOCP'].str.startswith('311'),
        dataframe['SOCP'].str.startswith('312'),
        dataframe['SOCP'].str.startswith('319'),
        dataframe['SOCP'].str.startswith('331'),
        dataframe['SOCP'].str.startswith('332'),
        dataframe['SOCP'].str.startswith('333'),
        dataframe['SOCP'].str.startswith('339'),
        dataframe['SOCP'].str.startswith('351'),#20
        dataframe['SOCP'].str.startswith('352'),
        dataframe['SOCP'].str.startswith('353'),
        dataframe['SOCP'].str.startswith('359'),
        dataframe['SOCP'].str.startswith('371'),
        dataframe['SOCP'].str.startswith('372'),
        dataframe['SOCP'].str.startswith('373'),
        dataframe['SOCP'].str.startswith('391'),
        dataframe['SOCP'].str.startswith('392'),
        dataframe['SOCP'].str.startswith('393'),
        dataframe['SOCP'].str.startswith('394'),
        dataframe['SOCP'].str.startswith('395'),
        dataframe['SOCP'].str.startswith('396'),
        dataframe['SOCP'].str.startswith('397'),
        dataframe['SOCP'].str.startswith('399'),
        dataframe['SOCP'].str.startswith('411'),
        dataframe['SOCP'].str.startswith('412'),
        dataframe['SOCP'].str.startswith('413'),
        dataframe['SOCP'].str.startswith('414'),
        dataframe['SOCP'].str.startswith('419'),
        dataframe['SOCP'].str.startswith('431'),#20
        dataframe['SOCP'].str.startswith('432'),
        dataframe['SOCP'].str.startswith('433'),
        dataframe['SOCP'].str.startswith('434'),
        dataframe['SOCP'].str.startswith('435'),
        dataframe['SOCP'].str.startswith('436'),
        dataframe['SOCP'].str.startswith('439'),
        dataframe['SOCP'].str.startswith('451'),
        dataframe['SOCP'].str.startswith('452'),
        dataframe['SOCP'].str.startswith('453'),
        dataframe['SOCP'].str.startswith('454'),
        dataframe['SOCP'].str.startswith('471'),
        dataframe['SOCP'].str.startswith('472'),
        dataframe['SOCP'].str.startswith('473'),
        dataframe['SOCP'].str.startswith('474'),
        dataframe['SOCP'].str.startswith('475'),
        dataframe['SOCP'].str.startswith('491'),
        dataframe['SOCP'].str.startswith('492'),
        dataframe['SOCP'].str.startswith('493'),
        dataframe['SOCP'].str.startswith('499'),
        dataframe['SOCP'].str.startswith('511'),#20
        dataframe['SOCP'].str.startswith('512'),
        dataframe['SOCP'].str.startswith('513'),
        dataframe['SOCP'].str.startswith('514'),
        dataframe['SOCP'].str.startswith('515'),
        dataframe['SOCP'].str.startswith('516'),
        dataframe['SOCP'].str.startswith('517'),
        dataframe['SOCP'].str.startswith('518'),
        dataframe['SOCP'].str.startswith('519'),
        dataframe['SOCP'].str.startswith('531'),
        dataframe['SOCP'].str.startswith('532'),
        dataframe['SOCP'].str.startswith('533'),
        dataframe['SOCP'].str.startswith('534'),
        dataframe['SOCP'].str.startswith('535'),
        dataframe['SOCP'].str.startswith('536'),
        dataframe['SOCP'].str.startswith('537'),
        dataframe['SOCP'].str.startswith('551'),
        dataframe['SOCP'].str.startswith('552'),
        dataframe['SOCP'].str.startswith('553'),
        dataframe['SOCP'].str.startswith('559'),
        dataframe['SOCP'].str.startswith('999'),#20
    ]
    choices = [
        'MGR1',
        'MGR2',
        'MGR3',
        'MGR4',
        'BUS1',
        'FIN1',
        'CMM1',
        'CMM2',
        'ENG1',
        'ENG2',
        'ENG3',
        'SCI1',
        'SCI2',
        'SCI3',
        'SCI4',
        'SCI5',
        'CMS1',
        'CMS2',
        'LGL1',
        'LGL2',#20
        'EDU1',
        'EDU2',
        'EDU3',
        'EDU4',
        'EDU5',
        'ENT1',
        'ENT2',
        'ENT3',
        'ENT4',
        'MED1',
        'MED2',
        'MED3',
        'HLS1',
        'HLS2',
        'HLS3',
        'PRT1',
        'PRT2',
        'PRT3',
        'PRT4',
        'EAT1',#20
        'EAT2',
        'EAT3',
        'EAT4',
        'CLN1',
        'CLN2',
        'CLN3',
        'PRS1',
        'PRS2',
        'PRS3',
        'PRS4',
        'PRS5',
        'PRS6',
        'PRS7',
        'PRS8',
        'SAL1',
        'SAL2',
        'SAL3',
        'SAL4',
        'SAL5',
        'OFF1',#20
        'OFF2',
        'OFF3',
        'OFF4',
        'OFF5',
        'OFF6',
        'OFF7',
        'FFF1',
        'FFF2',
        'FFF3',
        'FFF4',
        'EXT1',
        'EXT2',
        'EXT3',
        'EXT4',
        'EXT5',
        'PPR1',
        'PPR2',
        'PPR3',
        'PPR4',
        'PRD1',#20
        'PRD2',
        'PRD3',
        'PRD4',
        'PRD5',
        'PRD6',
        'PRD7',
        'PRD8',
        'PRD9',
        'TRN1',
        'TRN2',
        'TRN3',
        'TRN4',
        'TRN5',
        'TRN6',
        'TRN7',
        'MIL1',
        'MIL2',
        'MIL3',
        'MIL4',
        'No_Work'
    ]
    
    dataframe['SOCP'] = np.select(conditions, choices, 'No_Work')
    
    #drop all flags and weights
    dataframe.drop(columns =['FCITP', 'FDEYEP', 'FDOUTP',
       'FDPHYP', 'FDREMP', 'FENGP', 'FFERP', 'FFODP', 'FGCLP', 'FHINS1P',
       'FHINS3C', 'FHINS3P', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FINTP',
       'FJWDP', 'FJWRIP', 'FJWTRP', 'FLANXP', 'FMARHDP', 'FMARHMP',
       'FMARHWP', 'FMARHYP', 'FMIGP', 'FMILPP', 'FOCCP', 'FPAP', 'FPERNP',
       'FPINCP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSEMP', 'FWAGP', 'FWKLP',
       'FWKWP', 'FWRKP', 'PWGTP1', 'PWGTP2', 'PWGTP6', 'PWGTP7',
       'PWGTP11', 'PWGTP12', 'PWGTP13', 'PWGTP14', 'PWGTP15', 'PWGTP16',
       'PWGTP18', 'PWGTP19', 'PWGTP22', 'PWGTP27', 'PWGTP28', 'PWGTP29',
       'PWGTP33', 'PWGTP34', 'PWGTP35', 'PWGTP41', 'PWGTP44', 'PWGTP45',
       'PWGTP46', 'PWGTP49', 'PWGTP50', 'PWGTP53', 'PWGTP59', 'PWGTP60',
       'PWGTP62', 'PWGTP63', 'PWGTP64', 'PWGTP67', 'PWGTP69', 'PWGTP70',
       'PWGTP72', 'PWGTP73', 'PWGTP76', 'PWGTP78', 'PWGTP79'], inplace=True)

IndentationError: unexpected indent (<ipython-input-1-b812d48c6a56>, line 127)